// GENERATED by scripts/gen-block-entity-nbt.mjs from SpyglassMC/vanilla-mcdoc.
// Do not edit by hand - re-run `npm run gen:block-entity-nbt`.
import {
  asByte,
  asDoubles,
  asFloats,
  asList,
  asText,
  atLeast,
  defineBlockEntityNbt,
  field,
  type BlockEntityNbtSchema,
} from "./block-entity-nbt";
import { asItems, asPotDecorations, asSignText } from "./block-entity-nbt/fields";
import type {
  SlottedItems,
  SignTextInput,
  PotDecorationsInput,
} from "./block-entity-nbt/fields";
import { Byte, Double, Float, IntArray, Long, Short, type NbtInput } from "./nbt";
import type { ItemValue } from "./item";

export interface BlockEntityFields {
  components?: NbtInput;
}

export const BLOCK_ENTITY: BlockEntityNbtSchema<BlockEntityFields> = {
  components: field({ key: "components", since: "1.20.5" }),
};

export interface NameableFields {
  /** The custom name of this block. */
  customName?: string;
}

export const NAMEABLE: BlockEntityNbtSchema<NameableFields> = {
  customName: field({ key: "CustomName", encode: asText }),
};

export interface BannerFields extends BlockEntityFields, NameableFields {
  patterns?: readonly NbtInput[];
}

export const BANNER: BlockEntityNbtSchema<BannerFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  patterns: (v, version): Record<string, NbtInput> =>
    atLeast(version, "1.20.5")
      ? { patterns: asList(v) }
      : { Patterns: asList(v) },
};

export interface LockableFields {
  /** Item predicate testing the item that a player has to be holding to open this container. */
  lock?: NbtInput;
}

export const LOCKABLE: BlockEntityNbtSchema<LockableFields> = {
  lock: field({ key: "lock", since: "1.21.2", until: "1.21.2" }),
};

export interface BeaconFields extends BlockEntityFields, NameableFields, LockableFields {
  /** Number of levels from the pyramid. */
  levels?: number;
  /** Potion effect. */
  primary?: NbtInput;
  /** Potion effect. */
  secondary?: NbtInput;
  primaryEffect?: string;
  secondaryEffect?: string;
}

export const BEACON: BlockEntityNbtSchema<BeaconFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  ...LOCKABLE,
  levels: field({ key: "Levels" }),
  primary: field({ key: "Primary", until: "1.20.2" }),
  secondary: field({ key: "Secondary", until: "1.20.2" }),
  primaryEffect: field({ key: "primary_effect", since: "1.20.2" }),
  secondaryEffect: field({ key: "secondary_effect", since: "1.20.2" }),
};

export interface BeehiveFields extends BlockEntityFields {
  flowerPos?: readonly number[];
  bees?: readonly NbtInput[];
}

export const BEEHIVE: BlockEntityNbtSchema<BeehiveFields> = {
  ...BLOCK_ENTITY,
  flowerPos: field({ key: "flower_pos", encode: IntArray, since: "1.20.5", until: "1.20.5" }),
  bees: (v, version): Record<string, NbtInput> =>
    atLeast(version, "1.20.5")
      ? { bees: asList(v) }
      : { Bees: asList(v) },
};

export interface BrewingStandFields extends BlockEntityFields, NameableFields, LockableFields {
  /** * 0: left brewing slot * 1: middle brewing slot * 2: right brewing slot * 3: ingredient slot * 4: fuel slot */
  items?: SlottedItems;
  /** Number of ticks until the brewing is complete. */
  brewTime?: NbtInput;
  /** Amount of fuel the brewing stand has left. */
  fuel?: NbtInput;
  /** The total amount of time the current brewing process will take. Defaults to `400`. */
  totalBrewTime?: number;
  /** The amount of fuel that was added in the last refuel. Defaults to `20`. */
  totalFuel?: number;
  /** Used to speed up or slow down the next brewing process. Defaults to `1`. */
  speedMultiplier?: number;
}

export const BREWING_STAND: BlockEntityNbtSchema<BrewingStandFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  ...LOCKABLE,
  items: field({ key: "Items", encode: asItems }),
  brewTime: field({ key: "BrewTime" }),
  fuel: field({ key: "Fuel" }),
  totalBrewTime: field({ key: "total_brew_time", since: "26.3" }),
  totalFuel: field({ key: "total_fuel", since: "26.3" }),
  speedMultiplier: field({ key: "speed_multiplier", encode: Float, since: "26.3" }),
};

export interface BrushableBlockFields extends BlockEntityFields {
  /** Loot table that will decide the brushed loot. */
  lootTable?: string;
  /** Seed of the loot table. */
  lootTableSeed?: number;
  /** Item that was rolled from the loot table, which is currently peeking out. */
  item?: NbtInput;
  /** Direction of the block that was interacted with. Write-only, is not saved by the game. */
  hitDirection?: NbtInput;
}

export const BRUSHABLE_BLOCK: BlockEntityNbtSchema<BrushableBlockFields> = {
  ...BLOCK_ENTITY,
  lootTable: field({ key: "LootTable" }),
  lootTableSeed: field({ key: "LootTableSeed", encode: Long }),
  item: field({ key: "item" }),
  hitDirection: field({ key: "hit_direction" }),
};

export interface CampfireFields extends BlockEntityFields {
  items?: SlottedItems;
  /** Ticks each item has been cooking. Index is according to item slot. */
  cookingTimes?: readonly number[];
  /** Ticks each item still has to cook. Index is according to item slot. */
  cookingTotalTimes?: readonly number[];
}

export const CAMPFIRE: BlockEntityNbtSchema<CampfireFields> = {
  ...BLOCK_ENTITY,
  items: field({ key: "Items", encode: asItems }),
  cookingTimes: field({ key: "CookingTimes", encode: IntArray }),
  cookingTotalTimes: field({ key: "CookingTotalTimes", encode: IntArray }),
};

export interface ChiseledBookshelfFields extends BlockEntityFields {
  /** Slots from 0 to 5. */
  items?: SlottedItems;
  lastInteractedSlot?: number;
}

export const CHISELED_BOOKSHELF: BlockEntityNbtSchema<ChiseledBookshelfFields> = {
  ...BLOCK_ENTITY,
  items: field({ key: "Items", encode: asItems }),
  lastInteractedSlot: field({ key: "last_interacted_slot" }),
};

export interface BaseCommandBlockFields {
  /** The command to run. */
  command?: string;
  /** Success count of the last command. */
  successCount?: number;
  /** Output of the last command. */
  lastOutput?: string;
  /** Whether to record command output. */
  trackOutput?: boolean;
  /** Whether to record the tick of the latest command execution. */
  updateLastExecution?: boolean;
  /** Tick of the latest command execution. */
  lastExecution?: number;
}

export const BASE_COMMAND_BLOCK: BlockEntityNbtSchema<BaseCommandBlockFields> = {
  command: field({ key: "Command" }),
  successCount: field({ key: "SuccessCount" }),
  lastOutput: field({ key: "LastOutput", encode: asText }),
  trackOutput: field({ key: "TrackOutput", encode: asByte }),
  updateLastExecution: field({ key: "UpdateLastExecution", encode: asByte }),
  lastExecution: field({ key: "LastExecution", encode: Long }),
};

export interface CommandBlockFields extends BlockEntityFields, NameableFields, BaseCommandBlockFields {
  /** Whether it is powered by redstone. */
  powered?: boolean;
  /** Whether it is automatically powered. */
  auto?: boolean;
  /** Whether the previous command block was successful when the command block was executed. This is always true for non-conditional command blocks. */
  conditionMet?: boolean;
}

export const COMMAND_BLOCK: BlockEntityNbtSchema<CommandBlockFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  ...BASE_COMMAND_BLOCK,
  powered: field({ key: "powered", encode: asByte }),
  auto: field({ key: "auto", encode: asByte }),
  conditionMet: field({ key: "conditionMet", encode: asByte }),
};

export interface ComparatorFields extends BlockEntityFields {
  /** Strength of the redstone output. */
  outputSignal?: number;
}

export const COMPARATOR: BlockEntityNbtSchema<ComparatorFields> = {
  ...BLOCK_ENTITY,
  outputSignal: field({ key: "OutputSignal" }),
};

export interface ConduitFields extends BlockEntityFields {
  /** The hostile mob that the conduit is currently attacking. */
  targetUuid?: NbtInput;
  /** The hostile mob that the conduit is currently attacking. */
  target?: readonly number[];
}

export const CONDUIT: BlockEntityNbtSchema<ConduitFields> = {
  ...BLOCK_ENTITY,
  targetUuid: field({ key: "target_uuid", until: "1.16" }),
  target: field({ key: "Target", encode: IntArray, since: "1.16" }),
};

export interface ContainerBaseFields extends BlockEntityFields, NameableFields, LockableFields {
  /** Loot table that will populate this container. */
  lootTable?: string;
  /** Seed of the loot table. */
  lootTableSeed?: number;
}

export const CONTAINER_BASE: BlockEntityNbtSchema<ContainerBaseFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  ...LOCKABLE,
  lootTable: field({ key: "LootTable" }),
  lootTableSeed: field({ key: "LootTableSeed", encode: Long }),
};

export interface Container27Fields extends ContainerBaseFields {
  /** Slots from 0 to 26. */
  items?: SlottedItems;
}

export const CONTAINER27: BlockEntityNbtSchema<Container27Fields> = {
  ...CONTAINER_BASE,
  items: field({ key: "Items", encode: asItems }),
};

export interface Container9Fields extends ContainerBaseFields {
  /** Slots from 0 to 8. */
  items?: SlottedItems;
}

export const CONTAINER9: BlockEntityNbtSchema<Container9Fields> = {
  ...CONTAINER_BASE,
  items: field({ key: "Items", encode: asItems }),
};

export interface ShelfFields extends ContainerBaseFields {
  /** Slots from 0 to 2. */
  items?: SlottedItems;
  /** Defaults to `false`. */
  alignItemsToBottom?: boolean;
}

export const SHELF: BlockEntityNbtSchema<ShelfFields> = {
  ...CONTAINER_BASE,
  items: field({ key: "Items", encode: asItems }),
  alignItemsToBottom: field({ key: "align_items_to_bottom", encode: asByte }),
};

export interface HopperFields extends ContainerBaseFields {
  /** Slots from 0 to 4. */
  items?: SlottedItems;
  /** Ticks until an item can be transferred. */
  transferCooldown?: number;
}

export const HOPPER: BlockEntityNbtSchema<HopperFields> = {
  ...CONTAINER_BASE,
  items: field({ key: "Items", encode: asItems }),
  transferCooldown: field({ key: "TransferCooldown" }),
};

export interface CrafterFields extends Container9Fields {
  craftingTicksRemaining?: number;
  disabledSlots?: number;
  triggered?: NbtInput;
}

export const CRAFTER: BlockEntityNbtSchema<CrafterFields> = {
  ...CONTAINER9,
  craftingTicksRemaining: field({ key: "crafting_ticks_remaining" }),
  disabledSlots: field({ key: "disabled_slots" }),
  triggered: field({ key: "triggered" }),
};

export interface CreakingHeartFields extends BlockEntityFields {
  /** The creaking mob that is linked to this heart. */
  creaking?: readonly number[];
}

export const CREAKING_HEART: BlockEntityNbtSchema<CreakingHeartFields> = {
  ...BLOCK_ENTITY,
  creaking: field({ key: "creaking", encode: asList, since: "1.21.4" }),
};

export interface DecoratedPotFields extends BlockEntityFields {
  /** Item ID of what was used for each side of the pot. \ Decoration textures are determined by `provides_pottery_pattern` component on the sherd items. */
  sherds?: PotDecorationsInput;
  /** Loot table that will populate this container. */
  lootTable?: string;
  /** Seed of the loot table. */
  lootTableSeed?: number;
  item?: NbtInput;
}

export const DECORATED_POT: BlockEntityNbtSchema<DecoratedPotFields> = {
  ...BLOCK_ENTITY,
  sherds: field({ key: "sherds", encode: asPotDecorations, since: "26.3" }),
  lootTable: field({ key: "LootTable", since: "1.20.3" }),
  lootTableSeed: field({ key: "LootTableSeed", encode: Long, since: "1.20.3" }),
  item: field({ key: "item", since: "1.20.3" }),
};

export interface EnchantingTableFields extends BlockEntityFields, NameableFields {
}

export const ENCHANTING_TABLE: BlockEntityNbtSchema<EnchantingTableFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
};

export interface EndGatewayFields extends BlockEntityFields {
  /** In game ticks. */
  age?: number;
  /** Whether to teleport to the exact location. */
  exactTeleport?: boolean;
  /** Coordinates of where to teleport entities to. */
  exitPortal?: readonly number[];
}

export const END_GATEWAY: BlockEntityNbtSchema<EndGatewayFields> = {
  ...BLOCK_ENTITY,
  age: field({ key: "Age", encode: Long }),
  exactTeleport: field({ key: "ExactTeleport", encode: asByte }),
  exitPortal: field({ key: "exit_portal", encode: IntArray, since: "1.20.5", until: "1.20.5" }),
};

export interface FurnaceFields extends BlockEntityFields, NameableFields, LockableFields {
  /** The items in this furnace, with slots: * 0: Item being smelted * 1: Fuel * 2: Output */
  items?: SlottedItems;
  /** Ticks until the current fuel runs out. */
  burnTime?: number;
  /** Ticks the item has been smelting for. */
  cookTime?: number;
  /** Total ticks the item will take to be smelted. */
  cookTimeTotal?: number;
  /** The total amount of time the current cooking process will take. Defaults to `0`. */
  cookingTotalTime?: NbtInput;
  /** The amount of time that the current cooking process has taken so far. Defaults to `0`. */
  cookingTimeSpent?: NbtInput;
  /** The amount of burn time remaining. Defaults to `0`. */
  litTimeRemaining?: NbtInput;
  /** The total amount of burn time that was added in the last refuel. Defaults to `0`. */
  litTotalTime?: NbtInput;
  /** Used to speed up or slow down the next cooking process. Defaults to `1`. */
  speedMultiplier?: number;
  /** Recipes that have been used since the last time a result item was removed from the GUI. Used to calculate the experience to give to the player. */
  recipesUsed?: NbtInput;
}

export const FURNACE: BlockEntityNbtSchema<FurnaceFields> = {
  ...BLOCK_ENTITY,
  ...NAMEABLE,
  ...LOCKABLE,
  items: field({ key: "Items", encode: asItems }),
  burnTime: field({ key: "BurnTime", encode: Short, until: "1.21.4" }),
  cookTime: field({ key: "CookTime", encode: Short, until: "1.21.4" }),
  cookTimeTotal: field({ key: "CookTimeTotal", encode: Short, until: "1.21.4" }),
  cookingTotalTime: field({ key: "cooking_total_time", since: "1.21.4" }),
  cookingTimeSpent: field({ key: "cooking_time_spent", since: "1.21.4" }),
  litTimeRemaining: field({ key: "lit_time_remaining", since: "1.21.4" }),
  litTotalTime: field({ key: "lit_total_time", since: "1.21.4" }),
  speedMultiplier: field({ key: "speed_multiplier", encode: Float, since: "26.3" }),
  recipesUsed: field({ key: "RecipesUsed", since: "1.16" }),
};

export interface SkullFields extends BlockEntityFields {
  /** Owner of the skull. */
  owner?: NbtInput;
  skullOwner?: NbtInput;
  /** Name of the owner, if exists will be converted to SkullOwner. */
  extraType?: string;
  /** Sound to play when played with a note block. Only works on player head. */
  noteBlockSound?: NbtInput;
  /** Only works on player head. */
  profile?: NbtInput;
  customName?: NbtInput;
}

export const SKULL: BlockEntityNbtSchema<SkullFields> = {
  ...BLOCK_ENTITY,
  owner: field({ key: "Owner", until: "1.16" }),
  skullOwner: field({ key: "SkullOwner", since: "1.16", until: "1.20.5" }),
  extraType: field({ key: "ExtraType" }),
  noteBlockSound: field({ key: "note_block_sound", since: "1.19.3" }),
  profile: field({ key: "profile", since: "1.20.5" }),
  customName: field({ key: "custom_name", since: "1.20.5" }),
};

export interface JigsawFields {
  /** Structure pool this will connect to. */
  targetPool?: string;
  /** How the resultant structure can be transformed. */
  joint?: NbtInput;
  /** Structure pool this will "spawn" in. */
  pool?: string;
  /** ID this will "spawn" in. */
  name?: string;
  /** ID of the type of jigsaw this will be "spawned" from. */
  target?: string;
  /** Final block state of the jigsaw. */
  finalState?: string;
  /** ID of the type of jigsaw this connects to. */
  attachmentType?: string;
}

export const JIGSAW: BlockEntityNbtSchema<JigsawFields> = {
  targetPool: field({ key: "target_pool", until: "1.16" }),
  joint: field({ key: "joint", since: "1.16" }),
  pool: field({ key: "pool", since: "1.16" }),
  name: field({ key: "name", since: "1.16" }),
  target: field({ key: "target", since: "1.16" }),
  finalState: field({ key: "final_state" }),
  attachmentType: field({ key: "attachment_type", until: "1.16" }),
};

export interface JukeboxFields extends BlockEntityFields {
  recordItem?: ItemValue;
  tickCount?: number;
  recordStartTick?: number;
  isPlaying?: boolean;
  ticksSinceSongStarted?: number;
}

export const JUKEBOX: BlockEntityNbtSchema<JukeboxFields> = {
  ...BLOCK_ENTITY,
  recordItem: field({ key: "RecordItem", encode: (v: ItemValue) => v.stackNbt() }),
  tickCount: field({ key: "TickCount", encode: Long, until: "1.21" }),
  recordStartTick: field({ key: "RecordStartTick", encode: Long, until: "1.21" }),
  isPlaying: field({ key: "IsPlaying", encode: asByte, until: "1.21" }),
  ticksSinceSongStarted: field({ key: "ticks_since_song_started", encode: Long, since: "1.21" }),
};

export interface LecternFields extends BlockEntityFields {
  book?: NbtInput;
  /** Current page the book is on. */
  page?: number;
}

export const LECTERN: BlockEntityNbtSchema<LecternFields> = {
  ...BLOCK_ENTITY,
  book: field({ key: "Book" }),
  page: field({ key: "Page" }),
};

export interface MovingPistonFields extends BlockEntityFields {
  /** Moving block represented by the moving piston. */
  blockState?: NbtInput;
  /** The direction it is moving. */
  facing?: NbtInput;
  /** How far it has moved. */
  progress?: number;
  extending?: boolean;
  /** Whether the moving piston is the piston head. */
  source?: boolean;
}

export const MOVING_PISTON: BlockEntityNbtSchema<MovingPistonFields> = {
  ...BLOCK_ENTITY,
  blockState: field({ key: "blockState" }),
  facing: field({ key: "facing" }),
  progress: field({ key: "progress", encode: Float }),
  extending: field({ key: "extending", encode: asByte }),
  source: field({ key: "source", encode: asByte }),
};

export interface PotentSulfurFields extends BlockEntityFields {
  /** Time in seconds until the next state switch (between dormant and erupting). \ The timer only counts down when the potent sulfur creates a valid geyser. \ Negative values will be replaced with a new duration of the current state. */
  countdown?: number;
}

export const POTENT_SULFUR: BlockEntityNbtSchema<PotentSulfurFields> = {
  ...BLOCK_ENTITY,
  countdown: field({ key: "countdown" }),
};

export interface SculkCatalystFields extends BlockEntityFields {
  cursors?: readonly NbtInput[];
}

export const SCULK_CATALYST: BlockEntityNbtSchema<SculkCatalystFields> = {
  ...BLOCK_ENTITY,
  cursors: field({ key: "cursors", encode: asList }),
};

export interface SculkSensorFields {
  lastVibrationFrequency?: number;
  /** Vibration listener */
  listener?: NbtInput;
}

export const SCULK_SENSOR: BlockEntityNbtSchema<SculkSensorFields> = {
  lastVibrationFrequency: field({ key: "last_vibration_frequency" }),
  listener: field({ key: "listener", since: "1.19" }),
};

export interface SculkShriekerFields {
  warningLevel?: number;
  listener?: NbtInput;
}

export const SCULK_SHRIEKER: BlockEntityNbtSchema<SculkShriekerFields> = {
  warningLevel: field({ key: "warning_level" }),
  listener: field({ key: "listener" }),
};

export interface SignFields extends BlockEntityFields {
  backText?: SignTextInput;
  frontText?: SignTextInput;
  /** Whether the sign has been made uneditable by applying wax. */
  isWaxed?: boolean;
  /** Whether the sign allows following features: 1. Resolving text components 2. Executing click events  Defaults to `false`. */
  allowOpFeatures?: boolean;
}

export const SIGN: BlockEntityNbtSchema<SignFields> = {
  ...BLOCK_ENTITY,
  backText: field({ key: "back_text", encode: asSignText }),
  frontText: field({ key: "front_text", encode: asSignText }),
  isWaxed: field({ key: "is_waxed", encode: asByte }),
  allowOpFeatures: field({ key: "allow_op_features", encode: asByte, since: "26.3" }),
};

export interface SpawnerFields extends BlockEntityFields {
  /** Entities that can be placed. */
  spawnPotentials?: readonly NbtInput[];
  /** Data for the next mob to spawn. Overwritten by `SpawnPotentials`. */
  spawnData?: NbtInput;
  /** Number of entities that will be placed. */
  spawnCount?: number;
  /** Range that the spawned entities will be placed. */
  spawnRange?: number;
  /** Ticks until the next spawn. */
  delay?: number;
  /** Minimum random delay for the next spawn. */
  minSpawnDelay?: number;
  /** Maximum random delay for the next spawn. */
  maxSpawnDelay?: number;
  /** Maximum number of entities nearby. */
  maxNearbyEntities?: number;
  /** Radius in blocks that a player has to be within to spawn entities. */
  requiredPlayerRange?: number;
}

export const SPAWNER: BlockEntityNbtSchema<SpawnerFields> = {
  ...BLOCK_ENTITY,
  spawnPotentials: field({ key: "SpawnPotentials", encode: asList }),
  spawnData: field({ key: "SpawnData" }),
  spawnCount: field({ key: "SpawnCount", encode: Short }),
  spawnRange: field({ key: "SpawnRange", encode: Short }),
  delay: field({ key: "Delay", encode: Short }),
  minSpawnDelay: field({ key: "MinSpawnDelay", encode: Short }),
  maxSpawnDelay: field({ key: "MaxSpawnDelay", encode: Short }),
  maxNearbyEntities: field({ key: "MaxNearbyEntities", encode: Short }),
  requiredPlayerRange: field({ key: "RequiredPlayerRange", encode: Short }),
};

export interface TrialSpawnerFields {
  /** Spawning behavior when the player does not have the Bad Omen effect. */
  normalConfig?: NbtInput;
  /** Spawning behavior when the player has the Bad Omen effect. */
  ominousConfig?: NbtInput;
  /** Maximum distance for players to activate the trial spawner, or join a battle */
  requiredPlayerRange?: number;
  /** Time in ticks for the cooldown period. Included the time spend dispensing the reward. */
  targetCooldownLength?: number;
  /** Players that are have been nearby during the current battle */
  registeredPlayers?: readonly NbtInput[];
  /** All mobs that have been spawned by this trial spawner and are currently alive */
  currentMobs?: readonly NbtInput[];
  /** Gametime in ticks when the cooldown ends */
  cooldownEndsAt?: number;
  /** Gametime in ticks when the next spawning attempt happens */
  nextMobSpawnsAt?: number;
  totalMobsSpawned?: number;
  /** The next entity to spawn, also controlls the entity displayed in the trial spawner */
  spawnData?: NbtInput;
  /** The loot table selected to be used to determine the reward */
  ejectingLootTable?: string;
}

export const TRIAL_SPAWNER: BlockEntityNbtSchema<TrialSpawnerFields> = {
  normalConfig: field({ key: "normal_config" }),
  ominousConfig: field({ key: "ominous_config" }),
  requiredPlayerRange: field({ key: "required_player_range" }),
  targetCooldownLength: field({ key: "target_cooldown_length" }),
  registeredPlayers: field({ key: "registered_players", encode: asList }),
  currentMobs: field({ key: "current_mobs", encode: asList }),
  cooldownEndsAt: field({ key: "cooldown_ends_at", encode: Long }),
  nextMobSpawnsAt: field({ key: "next_mob_spawns_at", encode: Long }),
  totalMobsSpawned: field({ key: "total_mobs_spawned" }),
  spawnData: field({ key: "spawn_data" }),
  ejectingLootTable: field({ key: "ejecting_loot_table" }),
};

export interface StructureBlockFields extends BlockEntityFields {
  name?: string;
  /** Author of the structure. */
  author?: string;
  /** Custom data for the structure. Stores the data id for "DATA" mode. */
  metadata?: string;
  /** Relative offset. */
  posX?: number;
  /** Relative offset. */
  posY?: number;
  /** Relative offset. */
  posZ?: number;
  sizeX?: number;
  sizeY?: number;
  sizeZ?: number;
  rotation?: NbtInput;
  mirror?: NbtInput;
  mode?: NbtInput;
  ignoreEntities?: boolean;
  /** Whether to show the bounding box. */
  showboundingbox?: boolean;
  /** Whether it has been powered by redstone. */
  powered?: boolean;
  /** Whether to show invisible blocks inside the bounding box. */
  showair?: boolean;
  /** If set to `true`, the blocks in the placed structure will trigger block (entity) updates and shape updates. Defaults to `false`. */
  strict?: boolean;
  /** Chance for each block to stay. */
  integrity?: number;
  /** Seed for the integrity random. */
  seed?: number;
}

export const STRUCTURE_BLOCK: BlockEntityNbtSchema<StructureBlockFields> = {
  ...BLOCK_ENTITY,
  name: field({ key: "name" }),
  author: field({ key: "author" }),
  metadata: field({ key: "metadata" }),
  posX: field({ key: "posX" }),
  posY: field({ key: "posY" }),
  posZ: field({ key: "posZ" }),
  sizeX: field({ key: "sizeX" }),
  sizeY: field({ key: "sizeY" }),
  sizeZ: field({ key: "sizeZ" }),
  rotation: field({ key: "rotation" }),
  mirror: field({ key: "mirror" }),
  mode: field({ key: "mode" }),
  ignoreEntities: field({ key: "ignoreEntities", encode: asByte }),
  showboundingbox: field({ key: "showboundingbox", encode: asByte }),
  powered: field({ key: "powered", encode: asByte }),
  showair: field({ key: "showair", encode: asByte }),
  strict: field({ key: "strict", encode: asByte, since: "1.21.5" }),
  integrity: field({ key: "integrity", encode: Float }),
  seed: field({ key: "seed", encode: Long }),
};

export interface TestBlockFields extends BlockEntityFields {
  mode?: NbtInput;
  message?: string;
  powered?: boolean;
}

export const TEST_BLOCK: BlockEntityNbtSchema<TestBlockFields> = {
  ...BLOCK_ENTITY,
  mode: field({ key: "mode" }),
  message: field({ key: "message" }),
  powered: field({ key: "powered", encode: asByte }),
};

export interface TestInstanceBlockFields extends BlockEntityFields {
  data?: string;
  errors?: readonly NbtInput[];
}

export const TEST_INSTANCE_BLOCK: BlockEntityNbtSchema<TestInstanceBlockFields> = {
  ...BLOCK_ENTITY,
  data: field({ key: "data", encode: asText }),
  errors: field({ key: "errors", encode: asList, since: "1.21.9" }),
};

export interface VaultFields {
  serverData?: NbtInput;
  config?: NbtInput;
  /** When a player is in range of the vault, the same display item will be shown to all players. This is also used for the items that are being ejected from the vault. */
  sharedData?: NbtInput;
}

export const VAULT: BlockEntityNbtSchema<VaultFields> = {
  serverData: field({ key: "server_data" }),
  config: field({ key: "config" }),
  sharedData: field({ key: "shared_data" }),
};

/** `minecraft:banner` */
export const Banner = defineBlockEntityNbt<BannerFields>(BANNER, "minecraft:banner");

/** `minecraft:beacon` */
export const Beacon = defineBlockEntityNbt<BeaconFields>(BEACON, "minecraft:beacon");

/** `minecraft:beehive` */
export const Beehive = defineBlockEntityNbt<BeehiveFields>(BEEHIVE, "minecraft:beehive");

/** `minecraft:brewing_stand` */
export const BrewingStand = defineBlockEntityNbt<BrewingStandFields>(BREWING_STAND, "minecraft:brewing_stand");

/** `minecraft:suspicious_sand` */
export const SuspiciousSand = defineBlockEntityNbt<BrushableBlockFields>(BRUSHABLE_BLOCK, "minecraft:suspicious_sand");

/** `minecraft:brushable_block` */
export const BrushableBlock = defineBlockEntityNbt<BrushableBlockFields>(BRUSHABLE_BLOCK, "minecraft:brushable_block");

/** `minecraft:campfire` */
export const Campfire = defineBlockEntityNbt<CampfireFields>(CAMPFIRE, "minecraft:campfire");

/** `minecraft:chiseled_bookshelf` */
export const ChiseledBookshelf = defineBlockEntityNbt<ChiseledBookshelfFields>(CHISELED_BOOKSHELF, "minecraft:chiseled_bookshelf");

/** `minecraft:command_block` */
export const CommandBlock = defineBlockEntityNbt<CommandBlockFields>(COMMAND_BLOCK, "minecraft:command_block");

/** `minecraft:comparator` */
export const Comparator = defineBlockEntityNbt<ComparatorFields>(COMPARATOR, "minecraft:comparator");

/** `minecraft:conduit` */
export const Conduit = defineBlockEntityNbt<ConduitFields>(CONDUIT, "minecraft:conduit");

/** `minecraft:barrel` */
export const Barrel = defineBlockEntityNbt<Container27Fields>(CONTAINER27, "minecraft:barrel");

/** `minecraft:chest` */
export const Chest = defineBlockEntityNbt<Container27Fields>(CONTAINER27, "minecraft:chest");

/** `minecraft:trapped_chest` */
export const TrappedChest = defineBlockEntityNbt<Container27Fields>(CONTAINER27, "minecraft:trapped_chest");

/** `minecraft:shulker_box` */
export const ShulkerBox = defineBlockEntityNbt<Container27Fields>(CONTAINER27, "minecraft:shulker_box");

/** `minecraft:dispenser` */
export const Dispenser = defineBlockEntityNbt<Container9Fields>(CONTAINER9, "minecraft:dispenser");

/** `minecraft:dropper` */
export const Dropper = defineBlockEntityNbt<Container9Fields>(CONTAINER9, "minecraft:dropper");

/** `minecraft:shelf` */
export const Shelf = defineBlockEntityNbt<ShelfFields>(SHELF, "minecraft:shelf");

/** `minecraft:hopper` */
export const Hopper = defineBlockEntityNbt<HopperFields>(HOPPER, "minecraft:hopper");

/** `minecraft:crafter` */
export const Crafter = defineBlockEntityNbt<CrafterFields>(CRAFTER, "minecraft:crafter");

/** `minecraft:creaking_heart` */
export const CreakingHeart = defineBlockEntityNbt<CreakingHeartFields>(CREAKING_HEART, "minecraft:creaking_heart");

/** `minecraft:decorated_pot` */
export const DecoratedPot = defineBlockEntityNbt<DecoratedPotFields>(DECORATED_POT, "minecraft:decorated_pot");

/** `minecraft:enchanting_table` */
export const EnchantingTable = defineBlockEntityNbt<EnchantingTableFields>(ENCHANTING_TABLE, "minecraft:enchanting_table");

/** `minecraft:end_gateway` */
export const EndGateway = defineBlockEntityNbt<EndGatewayFields>(END_GATEWAY, "minecraft:end_gateway");

/** `minecraft:furnace` */
export const Furnace = defineBlockEntityNbt<FurnaceFields>(FURNACE, "minecraft:furnace");

/** `minecraft:blast_furnace` */
export const BlastFurnace = defineBlockEntityNbt<FurnaceFields>(FURNACE, "minecraft:blast_furnace");

/** `minecraft:smoker` */
export const Smoker = defineBlockEntityNbt<FurnaceFields>(FURNACE, "minecraft:smoker");

/** `minecraft:skull` */
export const Skull = defineBlockEntityNbt<SkullFields>(SKULL, "minecraft:skull");

/** `minecraft:jigsaw` */
export const Jigsaw = defineBlockEntityNbt<JigsawFields>(JIGSAW, "minecraft:jigsaw");

/** `minecraft:jukebox` */
export const Jukebox = defineBlockEntityNbt<JukeboxFields>(JUKEBOX, "minecraft:jukebox");

/** `minecraft:lectern` */
export const Lectern = defineBlockEntityNbt<LecternFields>(LECTERN, "minecraft:lectern");

/** `minecraft:moving_piston` */
export const MovingPiston = defineBlockEntityNbt<MovingPistonFields>(MOVING_PISTON, "minecraft:moving_piston");

/** `minecraft:potent_sulfur` */
export const PotentSulfur = defineBlockEntityNbt<PotentSulfurFields>(POTENT_SULFUR, "minecraft:potent_sulfur");

/** `minecraft:sculk_catalyst` */
export const SculkCatalyst = defineBlockEntityNbt<SculkCatalystFields>(SCULK_CATALYST, "minecraft:sculk_catalyst");

/** `minecraft:sculk_sensor` */
export const SculkSensor = defineBlockEntityNbt<SculkSensorFields>(SCULK_SENSOR, "minecraft:sculk_sensor");

/** `minecraft:calibrated_sculk_sensor` */
export const CalibratedSculkSensor = defineBlockEntityNbt<SculkSensorFields>(SCULK_SENSOR, "minecraft:calibrated_sculk_sensor");

/** `minecraft:sculk_shrieker` */
export const SculkShrieker = defineBlockEntityNbt<SculkShriekerFields>(SCULK_SHRIEKER, "minecraft:sculk_shrieker");

/** `minecraft:sign` */
export const Sign = defineBlockEntityNbt<SignFields>(SIGN, "minecraft:sign");

/** `minecraft:hanging_sign` */
export const HangingSign = defineBlockEntityNbt<SignFields>(SIGN, "minecraft:hanging_sign");

/** `minecraft:mob_spawner` */
export const MobSpawner = defineBlockEntityNbt<SpawnerFields>(SPAWNER, "minecraft:mob_spawner");

/** `minecraft:trial_spawner` */
export const TrialSpawner = defineBlockEntityNbt<TrialSpawnerFields>(TRIAL_SPAWNER, "minecraft:trial_spawner");

/** `minecraft:structure_block` */
export const StructureBlock = defineBlockEntityNbt<StructureBlockFields>(STRUCTURE_BLOCK, "minecraft:structure_block");

/** `minecraft:test_block` */
export const TestBlock = defineBlockEntityNbt<TestBlockFields>(TEST_BLOCK, "minecraft:test_block");

/** `minecraft:test_instance_block` */
export const TestInstanceBlock = defineBlockEntityNbt<TestInstanceBlockFields>(TEST_INSTANCE_BLOCK, "minecraft:test_instance_block");

/** `minecraft:vault` */
export const Vault = defineBlockEntityNbt<VaultFields>(VAULT, "minecraft:vault");

/** The factory curating each block entity type, for the raw-NBT warning. */
export const BLOCK_ENTITY_FACTORY_NAMES: Readonly<Record<string, string>> = {
  "minecraft:banner": "Banner",
  "minecraft:beacon": "Beacon",
  "minecraft:beehive": "Beehive",
  "minecraft:brewing_stand": "BrewingStand",
  "minecraft:suspicious_sand": "SuspiciousSand",
  "minecraft:brushable_block": "BrushableBlock",
  "minecraft:campfire": "Campfire",
  "minecraft:chiseled_bookshelf": "ChiseledBookshelf",
  "minecraft:command_block": "CommandBlock",
  "minecraft:comparator": "Comparator",
  "minecraft:conduit": "Conduit",
  "minecraft:barrel": "Barrel",
  "minecraft:chest": "Chest",
  "minecraft:trapped_chest": "TrappedChest",
  "minecraft:shulker_box": "ShulkerBox",
  "minecraft:dispenser": "Dispenser",
  "minecraft:dropper": "Dropper",
  "minecraft:shelf": "Shelf",
  "minecraft:hopper": "Hopper",
  "minecraft:crafter": "Crafter",
  "minecraft:creaking_heart": "CreakingHeart",
  "minecraft:decorated_pot": "DecoratedPot",
  "minecraft:enchanting_table": "EnchantingTable",
  "minecraft:end_gateway": "EndGateway",
  "minecraft:furnace": "Furnace",
  "minecraft:blast_furnace": "BlastFurnace",
  "minecraft:smoker": "Smoker",
  "minecraft:skull": "Skull",
  "minecraft:jigsaw": "Jigsaw",
  "minecraft:jukebox": "Jukebox",
  "minecraft:lectern": "Lectern",
  "minecraft:moving_piston": "MovingPiston",
  "minecraft:potent_sulfur": "PotentSulfur",
  "minecraft:sculk_catalyst": "SculkCatalyst",
  "minecraft:sculk_sensor": "SculkSensor",
  "minecraft:calibrated_sculk_sensor": "CalibratedSculkSensor",
  "minecraft:sculk_shrieker": "SculkShrieker",
  "minecraft:sign": "Sign",
  "minecraft:hanging_sign": "HangingSign",
  "minecraft:mob_spawner": "MobSpawner",
  "minecraft:trial_spawner": "TrialSpawner",
  "minecraft:structure_block": "StructureBlock",
  "minecraft:test_block": "TestBlock",
  "minecraft:test_instance_block": "TestInstanceBlock",
  "minecraft:vault": "Vault",
};

/** Every block id's block_entity_type, for the compile-time `.data()` map and the runtime warning. */
export const BLOCK_ID_TO_BLOCK_ENTITY_TYPE: Readonly<Record<string, string>> = {
  "minecraft:white_banner": "minecraft:banner",
  "minecraft:orange_banner": "minecraft:banner",
  "minecraft:magenta_banner": "minecraft:banner",
  "minecraft:light_blue_banner": "minecraft:banner",
  "minecraft:yellow_banner": "minecraft:banner",
  "minecraft:lime_banner": "minecraft:banner",
  "minecraft:pink_banner": "minecraft:banner",
  "minecraft:gray_banner": "minecraft:banner",
  "minecraft:light_gray_banner": "minecraft:banner",
  "minecraft:cyan_banner": "minecraft:banner",
  "minecraft:purple_banner": "minecraft:banner",
  "minecraft:blue_banner": "minecraft:banner",
  "minecraft:brown_banner": "minecraft:banner",
  "minecraft:green_banner": "minecraft:banner",
  "minecraft:red_banner": "minecraft:banner",
  "minecraft:black_banner": "minecraft:banner",
  "minecraft:white_wall_banner": "minecraft:banner",
  "minecraft:orange_wall_banner": "minecraft:banner",
  "minecraft:magenta_wall_banner": "minecraft:banner",
  "minecraft:light_blue_wall_banner": "minecraft:banner",
  "minecraft:yellow_wall_banner": "minecraft:banner",
  "minecraft:lime_wall_banner": "minecraft:banner",
  "minecraft:pink_wall_banner": "minecraft:banner",
  "minecraft:gray_wall_banner": "minecraft:banner",
  "minecraft:light_gray_wall_banner": "minecraft:banner",
  "minecraft:cyan_wall_banner": "minecraft:banner",
  "minecraft:purple_wall_banner": "minecraft:banner",
  "minecraft:blue_wall_banner": "minecraft:banner",
  "minecraft:brown_wall_banner": "minecraft:banner",
  "minecraft:green_wall_banner": "minecraft:banner",
  "minecraft:red_wall_banner": "minecraft:banner",
  "minecraft:black_wall_banner": "minecraft:banner",
  "minecraft:beacon": "minecraft:beacon",
  "minecraft:beehive": "minecraft:beehive",
  "minecraft:bee_nest": "minecraft:beehive",
  "minecraft:brewing_stand": "minecraft:brewing_stand",
  "minecraft:suspicious_sand": "minecraft:brushable_block",
  "minecraft:suspicious_gravel": "minecraft:brushable_block",
  "minecraft:campfire": "minecraft:campfire",
  "minecraft:soul_campfire": "minecraft:campfire",
  "minecraft:chiseled_bookshelf": "minecraft:chiseled_bookshelf",
  "minecraft:command_block": "minecraft:command_block",
  "minecraft:chain_command_block": "minecraft:command_block",
  "minecraft:repeating_command_block": "minecraft:command_block",
  "minecraft:comparator": "minecraft:comparator",
  "minecraft:conduit": "minecraft:conduit",
  "minecraft:barrel": "minecraft:barrel",
  "minecraft:chest": "minecraft:chest",
  "minecraft:copper_chest": "minecraft:chest",
  "minecraft:exposed_copper_chest": "minecraft:chest",
  "minecraft:weathered_copper_chest": "minecraft:chest",
  "minecraft:oxidized_copper_chest": "minecraft:chest",
  "minecraft:waxed_copper_chest": "minecraft:chest",
  "minecraft:waxed_exposed_copper_chest": "minecraft:chest",
  "minecraft:waxed_weathered_copper_chest": "minecraft:chest",
  "minecraft:waxed_oxidized_copper_chest": "minecraft:chest",
  "minecraft:trapped_chest": "minecraft:trapped_chest",
  "minecraft:shulker_box": "minecraft:shulker_box",
  "minecraft:white_shulker_box": "minecraft:shulker_box",
  "minecraft:orange_shulker_box": "minecraft:shulker_box",
  "minecraft:magenta_shulker_box": "minecraft:shulker_box",
  "minecraft:light_blue_shulker_box": "minecraft:shulker_box",
  "minecraft:yellow_shulker_box": "minecraft:shulker_box",
  "minecraft:lime_shulker_box": "minecraft:shulker_box",
  "minecraft:pink_shulker_box": "minecraft:shulker_box",
  "minecraft:gray_shulker_box": "minecraft:shulker_box",
  "minecraft:light_gray_shulker_box": "minecraft:shulker_box",
  "minecraft:cyan_shulker_box": "minecraft:shulker_box",
  "minecraft:purple_shulker_box": "minecraft:shulker_box",
  "minecraft:blue_shulker_box": "minecraft:shulker_box",
  "minecraft:brown_shulker_box": "minecraft:shulker_box",
  "minecraft:green_shulker_box": "minecraft:shulker_box",
  "minecraft:red_shulker_box": "minecraft:shulker_box",
  "minecraft:black_shulker_box": "minecraft:shulker_box",
  "minecraft:dispenser": "minecraft:dispenser",
  "minecraft:dropper": "minecraft:dispenser",
  "minecraft:oak_shelf": "minecraft:shelf",
  "minecraft:spruce_shelf": "minecraft:shelf",
  "minecraft:birch_shelf": "minecraft:shelf",
  "minecraft:jungle_shelf": "minecraft:shelf",
  "minecraft:acacia_shelf": "minecraft:shelf",
  "minecraft:dark_oak_shelf": "minecraft:shelf",
  "minecraft:mangrove_shelf": "minecraft:shelf",
  "minecraft:cherry_shelf": "minecraft:shelf",
  "minecraft:pale_oak_shelf": "minecraft:shelf",
  "minecraft:bamboo_shelf": "minecraft:shelf",
  "minecraft:crimson_shelf": "minecraft:shelf",
  "minecraft:warped_shelf": "minecraft:shelf",
  "minecraft:poplar_shelf": "minecraft:shelf",
  "minecraft:hopper": "minecraft:hopper",
  "minecraft:crafter": "minecraft:crafter",
  "minecraft:decorated_pot": "minecraft:decorated_pot",
  "minecraft:enchanting_table": "minecraft:enchanting_table",
  "minecraft:end_gateway": "minecraft:end_gateway",
  "minecraft:furnace": "minecraft:furnace",
  "minecraft:blast_furnace": "minecraft:blast_furnace",
  "minecraft:smoker": "minecraft:smoker",
  "minecraft:player_head": "minecraft:skull",
  "minecraft:player_wall_head": "minecraft:skull",
  "minecraft:jigsaw": "minecraft:jigsaw",
  "minecraft:jukebox": "minecraft:jukebox",
  "minecraft:lectern": "minecraft:lectern",
  "minecraft:moving_piston": "minecraft:moving_piston",
  "minecraft:potent_sulfur": "minecraft:potent_sulfur",
  "minecraft:sculk_catalyst": "minecraft:sculk_catalyst",
  "minecraft:sculk_sensor": "minecraft:sculk_sensor",
  "minecraft:calibrated_sculk_sensor": "minecraft:sculk_sensor",
  "minecraft:sculk_shrieker": "minecraft:sculk_shrieker",
  "minecraft:acacia_sign": "minecraft:sign",
  "minecraft:birch_sign": "minecraft:sign",
  "minecraft:dark_oak_sign": "minecraft:sign",
  "minecraft:jungle_sign": "minecraft:sign",
  "minecraft:oak_sign": "minecraft:sign",
  "minecraft:spruce_sign": "minecraft:sign",
  "minecraft:acacia_wall_sign": "minecraft:sign",
  "minecraft:birch_wall_sign": "minecraft:sign",
  "minecraft:dark_oak_wall_sign": "minecraft:sign",
  "minecraft:jungle_wall_sign": "minecraft:sign",
  "minecraft:oak_wall_sign": "minecraft:sign",
  "minecraft:spruce_wall_sign": "minecraft:sign",
  "minecraft:crimson_sign": "minecraft:sign",
  "minecraft:warped_sign": "minecraft:sign",
  "minecraft:crimson_wall_sign": "minecraft:sign",
  "minecraft:warped_wall_sign": "minecraft:sign",
  "minecraft:mangrove_sign": "minecraft:sign",
  "minecraft:mangrove_wall_sign": "minecraft:sign",
  "minecraft:bamboo_sign": "minecraft:sign",
  "minecraft:bamboo_wall_sign": "minecraft:sign",
  "minecraft:cherry_sign": "minecraft:sign",
  "minecraft:cherry_wall_sign": "minecraft:sign",
  "minecraft:pale_oak_sign": "minecraft:sign",
  "minecraft:pale_oak_wall_sign": "minecraft:sign",
  "minecraft:poplar_sign": "minecraft:sign",
  "minecraft:poplar_wall_sign": "minecraft:sign",
  "minecraft:acacia_hanging_sign": "minecraft:hanging_sign",
  "minecraft:bamboo_hanging_sign": "minecraft:hanging_sign",
  "minecraft:birch_hanging_sign": "minecraft:hanging_sign",
  "minecraft:crimson_hanging_sign": "minecraft:hanging_sign",
  "minecraft:dark_oak_hanging_sign": "minecraft:hanging_sign",
  "minecraft:jungle_hanging_sign": "minecraft:hanging_sign",
  "minecraft:mangrove_hanging_sign": "minecraft:hanging_sign",
  "minecraft:oak_hanging_sign": "minecraft:hanging_sign",
  "minecraft:spruce_hanging_sign": "minecraft:hanging_sign",
  "minecraft:warped_hanging_sign": "minecraft:hanging_sign",
  "minecraft:acacia_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:bamboo_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:birch_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:crimson_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:dark_oak_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:jungle_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:mangrove_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:oak_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:spruce_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:warped_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:cherry_hanging_sign": "minecraft:hanging_sign",
  "minecraft:cherry_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:pale_oak_hanging_sign": "minecraft:hanging_sign",
  "minecraft:pale_oak_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:poplar_hanging_sign": "minecraft:hanging_sign",
  "minecraft:poplar_wall_hanging_sign": "minecraft:hanging_sign",
  "minecraft:spawner": "minecraft:mob_spawner",
  "minecraft:trial_spawner": "minecraft:trial_spawner",
  "minecraft:structure_block": "minecraft:structure_block",
  "minecraft:test_block": "minecraft:test_block",
  "minecraft:test_instance_block": "minecraft:test_instance_block",
  "minecraft:vault": "minecraft:vault",
  "minecraft:skeleton_skull": "minecraft:skull",
  "minecraft:wither_skeleton_skull": "minecraft:skull",
  "minecraft:creeper_head": "minecraft:skull",
  "minecraft:zombie_head": "minecraft:skull",
  "minecraft:dragon_head": "minecraft:skull",
  "minecraft:skeleton_wall_skull": "minecraft:skull",
  "minecraft:wither_skeleton_wall_skull": "minecraft:skull",
  "minecraft:creeper_wall_head": "minecraft:skull",
  "minecraft:zombie_wall_head": "minecraft:skull",
  "minecraft:dragon_wall_head": "minecraft:skull",
};

/**
 * Every block id's typed `.data()` payload, keyed off {@link BLOCK_ID_TO_BLOCK_ENTITY_TYPE}.
 * `BlockValue.data()` uses this to hard-reject a bare `Nbt(...)`/string once a block's
 * type has a typed factory - see `block.ts`.
 */
export interface BlockEntityDataByBlockId {
  "minecraft:white_banner": ReturnType<typeof Banner>;
  "minecraft:orange_banner": ReturnType<typeof Banner>;
  "minecraft:magenta_banner": ReturnType<typeof Banner>;
  "minecraft:light_blue_banner": ReturnType<typeof Banner>;
  "minecraft:yellow_banner": ReturnType<typeof Banner>;
  "minecraft:lime_banner": ReturnType<typeof Banner>;
  "minecraft:pink_banner": ReturnType<typeof Banner>;
  "minecraft:gray_banner": ReturnType<typeof Banner>;
  "minecraft:light_gray_banner": ReturnType<typeof Banner>;
  "minecraft:cyan_banner": ReturnType<typeof Banner>;
  "minecraft:purple_banner": ReturnType<typeof Banner>;
  "minecraft:blue_banner": ReturnType<typeof Banner>;
  "minecraft:brown_banner": ReturnType<typeof Banner>;
  "minecraft:green_banner": ReturnType<typeof Banner>;
  "minecraft:red_banner": ReturnType<typeof Banner>;
  "minecraft:black_banner": ReturnType<typeof Banner>;
  "minecraft:white_wall_banner": ReturnType<typeof Banner>;
  "minecraft:orange_wall_banner": ReturnType<typeof Banner>;
  "minecraft:magenta_wall_banner": ReturnType<typeof Banner>;
  "minecraft:light_blue_wall_banner": ReturnType<typeof Banner>;
  "minecraft:yellow_wall_banner": ReturnType<typeof Banner>;
  "minecraft:lime_wall_banner": ReturnType<typeof Banner>;
  "minecraft:pink_wall_banner": ReturnType<typeof Banner>;
  "minecraft:gray_wall_banner": ReturnType<typeof Banner>;
  "minecraft:light_gray_wall_banner": ReturnType<typeof Banner>;
  "minecraft:cyan_wall_banner": ReturnType<typeof Banner>;
  "minecraft:purple_wall_banner": ReturnType<typeof Banner>;
  "minecraft:blue_wall_banner": ReturnType<typeof Banner>;
  "minecraft:brown_wall_banner": ReturnType<typeof Banner>;
  "minecraft:green_wall_banner": ReturnType<typeof Banner>;
  "minecraft:red_wall_banner": ReturnType<typeof Banner>;
  "minecraft:black_wall_banner": ReturnType<typeof Banner>;
  "minecraft:beacon": ReturnType<typeof Beacon>;
  "minecraft:beehive": ReturnType<typeof Beehive>;
  "minecraft:bee_nest": ReturnType<typeof Beehive>;
  "minecraft:brewing_stand": ReturnType<typeof BrewingStand>;
  "minecraft:suspicious_sand": ReturnType<typeof BrushableBlock>;
  "minecraft:suspicious_gravel": ReturnType<typeof BrushableBlock>;
  "minecraft:campfire": ReturnType<typeof Campfire>;
  "minecraft:soul_campfire": ReturnType<typeof Campfire>;
  "minecraft:chiseled_bookshelf": ReturnType<typeof ChiseledBookshelf>;
  "minecraft:command_block": ReturnType<typeof CommandBlock>;
  "minecraft:chain_command_block": ReturnType<typeof CommandBlock>;
  "minecraft:repeating_command_block": ReturnType<typeof CommandBlock>;
  "minecraft:comparator": ReturnType<typeof Comparator>;
  "minecraft:conduit": ReturnType<typeof Conduit>;
  "minecraft:barrel": ReturnType<typeof Barrel>;
  "minecraft:chest": ReturnType<typeof Chest>;
  "minecraft:copper_chest": ReturnType<typeof Chest>;
  "minecraft:exposed_copper_chest": ReturnType<typeof Chest>;
  "minecraft:weathered_copper_chest": ReturnType<typeof Chest>;
  "minecraft:oxidized_copper_chest": ReturnType<typeof Chest>;
  "minecraft:waxed_copper_chest": ReturnType<typeof Chest>;
  "minecraft:waxed_exposed_copper_chest": ReturnType<typeof Chest>;
  "minecraft:waxed_weathered_copper_chest": ReturnType<typeof Chest>;
  "minecraft:waxed_oxidized_copper_chest": ReturnType<typeof Chest>;
  "minecraft:trapped_chest": ReturnType<typeof TrappedChest>;
  "minecraft:shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:white_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:orange_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:magenta_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:light_blue_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:yellow_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:lime_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:pink_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:gray_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:light_gray_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:cyan_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:purple_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:blue_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:brown_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:green_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:red_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:black_shulker_box": ReturnType<typeof ShulkerBox>;
  "minecraft:dispenser": ReturnType<typeof Dispenser>;
  "minecraft:dropper": ReturnType<typeof Dispenser>;
  "minecraft:oak_shelf": ReturnType<typeof Shelf>;
  "minecraft:spruce_shelf": ReturnType<typeof Shelf>;
  "minecraft:birch_shelf": ReturnType<typeof Shelf>;
  "minecraft:jungle_shelf": ReturnType<typeof Shelf>;
  "minecraft:acacia_shelf": ReturnType<typeof Shelf>;
  "minecraft:dark_oak_shelf": ReturnType<typeof Shelf>;
  "minecraft:mangrove_shelf": ReturnType<typeof Shelf>;
  "minecraft:cherry_shelf": ReturnType<typeof Shelf>;
  "minecraft:pale_oak_shelf": ReturnType<typeof Shelf>;
  "minecraft:bamboo_shelf": ReturnType<typeof Shelf>;
  "minecraft:crimson_shelf": ReturnType<typeof Shelf>;
  "minecraft:warped_shelf": ReturnType<typeof Shelf>;
  "minecraft:poplar_shelf": ReturnType<typeof Shelf>;
  "minecraft:hopper": ReturnType<typeof Hopper>;
  "minecraft:crafter": ReturnType<typeof Crafter>;
  "minecraft:decorated_pot": ReturnType<typeof DecoratedPot>;
  "minecraft:enchanting_table": ReturnType<typeof EnchantingTable>;
  "minecraft:end_gateway": ReturnType<typeof EndGateway>;
  "minecraft:furnace": ReturnType<typeof Furnace>;
  "minecraft:blast_furnace": ReturnType<typeof BlastFurnace>;
  "minecraft:smoker": ReturnType<typeof Smoker>;
  "minecraft:player_head": ReturnType<typeof Skull>;
  "minecraft:player_wall_head": ReturnType<typeof Skull>;
  "minecraft:jigsaw": ReturnType<typeof Jigsaw>;
  "minecraft:jukebox": ReturnType<typeof Jukebox>;
  "minecraft:lectern": ReturnType<typeof Lectern>;
  "minecraft:moving_piston": ReturnType<typeof MovingPiston>;
  "minecraft:potent_sulfur": ReturnType<typeof PotentSulfur>;
  "minecraft:sculk_catalyst": ReturnType<typeof SculkCatalyst>;
  "minecraft:sculk_sensor": ReturnType<typeof SculkSensor>;
  "minecraft:calibrated_sculk_sensor": ReturnType<typeof SculkSensor>;
  "minecraft:sculk_shrieker": ReturnType<typeof SculkShrieker>;
  "minecraft:acacia_sign": ReturnType<typeof Sign>;
  "minecraft:birch_sign": ReturnType<typeof Sign>;
  "minecraft:dark_oak_sign": ReturnType<typeof Sign>;
  "minecraft:jungle_sign": ReturnType<typeof Sign>;
  "minecraft:oak_sign": ReturnType<typeof Sign>;
  "minecraft:spruce_sign": ReturnType<typeof Sign>;
  "minecraft:acacia_wall_sign": ReturnType<typeof Sign>;
  "minecraft:birch_wall_sign": ReturnType<typeof Sign>;
  "minecraft:dark_oak_wall_sign": ReturnType<typeof Sign>;
  "minecraft:jungle_wall_sign": ReturnType<typeof Sign>;
  "minecraft:oak_wall_sign": ReturnType<typeof Sign>;
  "minecraft:spruce_wall_sign": ReturnType<typeof Sign>;
  "minecraft:crimson_sign": ReturnType<typeof Sign>;
  "minecraft:warped_sign": ReturnType<typeof Sign>;
  "minecraft:crimson_wall_sign": ReturnType<typeof Sign>;
  "minecraft:warped_wall_sign": ReturnType<typeof Sign>;
  "minecraft:mangrove_sign": ReturnType<typeof Sign>;
  "minecraft:mangrove_wall_sign": ReturnType<typeof Sign>;
  "minecraft:bamboo_sign": ReturnType<typeof Sign>;
  "minecraft:bamboo_wall_sign": ReturnType<typeof Sign>;
  "minecraft:cherry_sign": ReturnType<typeof Sign>;
  "minecraft:cherry_wall_sign": ReturnType<typeof Sign>;
  "minecraft:pale_oak_sign": ReturnType<typeof Sign>;
  "minecraft:pale_oak_wall_sign": ReturnType<typeof Sign>;
  "minecraft:poplar_sign": ReturnType<typeof Sign>;
  "minecraft:poplar_wall_sign": ReturnType<typeof Sign>;
  "minecraft:acacia_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:bamboo_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:birch_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:crimson_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:dark_oak_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:jungle_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:mangrove_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:oak_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:spruce_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:warped_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:acacia_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:bamboo_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:birch_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:crimson_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:dark_oak_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:jungle_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:mangrove_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:oak_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:spruce_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:warped_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:cherry_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:cherry_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:pale_oak_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:pale_oak_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:poplar_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:poplar_wall_hanging_sign": ReturnType<typeof HangingSign>;
  "minecraft:spawner": ReturnType<typeof MobSpawner>;
  "minecraft:trial_spawner": ReturnType<typeof TrialSpawner>;
  "minecraft:structure_block": ReturnType<typeof StructureBlock>;
  "minecraft:test_block": ReturnType<typeof TestBlock>;
  "minecraft:test_instance_block": ReturnType<typeof TestInstanceBlock>;
  "minecraft:vault": ReturnType<typeof Vault>;
  "minecraft:skeleton_skull": ReturnType<typeof Skull>;
  "minecraft:wither_skeleton_skull": ReturnType<typeof Skull>;
  "minecraft:creeper_head": ReturnType<typeof Skull>;
  "minecraft:zombie_head": ReturnType<typeof Skull>;
  "minecraft:dragon_head": ReturnType<typeof Skull>;
  "minecraft:skeleton_wall_skull": ReturnType<typeof Skull>;
  "minecraft:wither_skeleton_wall_skull": ReturnType<typeof Skull>;
  "minecraft:creeper_wall_head": ReturnType<typeof Skull>;
  "minecraft:zombie_wall_head": ReturnType<typeof Skull>;
  "minecraft:dragon_wall_head": ReturnType<typeof Skull>;
}
