// GENERATED by scripts/gen-entity-nbt.mjs from misode/mcmeta.
/** The dataVersion each version gated by an entity schema starts at. */
export const DV = {
  "1.16": 2566,
  "1.16.2": 2578,
  "1.17": 2724,
  "1.19": 3105,
  "1.20": 3463,
  "1.20.2": 3578,
  "1.20.3": 3698,
  "1.20.5": 3837,
  "1.21": 3953,
  "1.21.11": 4671,
  "1.21.2": 4080,
  "1.21.4": 4189,
  "1.21.5": 4325,
  "1.21.6": 4435,
  "1.21.9": 4554,
  "26.1": 4786,
  "26.2": 4903,
  "26.3": 99999999,
} as const;
