// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
// One named, branded resource type per registry referenced by a command arg.
// See values/resource.ts for the `ResourceId<R>` base and the rationale.
// Registries with enumerable contents also expose typed members (e.g.
// `Enchantment.SHARPNESS`); custom / tagged ids still use the call form.
import { ResourceId } from "./resource";
import { withMembers } from "./members";
import { ATTRIBUTE_IDS, DAMAGE_TYPE_IDS, DIMENSION_IDS, ENCHANTMENT_IDS, ENTITY_TYPE_IDS, MOB_EFFECT_IDS, PARTICLE_TYPE_IDS, POINT_OF_INTEREST_TYPE_IDS, WORLDGEN_BIOME_IDS, WORLDGEN_STRUCTURE_IDS } from "../../versions/data/ids";

export type Advancement = ResourceId<"minecraft:advancement">;
export const Advancement = (id: string): Advancement => new ResourceId(id, "minecraft:advancement");

export type Attribute = ResourceId<"minecraft:attribute">;
export const Attribute = withMembers(
  (id: string): Attribute => new ResourceId(id, "minecraft:attribute"),
  ATTRIBUTE_IDS,
  (id) => new ResourceId(id, "minecraft:attribute"),
);

export type Biome = ResourceId<"minecraft:worldgen/biome">;
export const Biome = withMembers(
  (id: string): Biome => new ResourceId(id, "minecraft:worldgen/biome"),
  WORLDGEN_BIOME_IDS,
  (id) => new ResourceId(id, "minecraft:worldgen/biome"),
);

export type ConfiguredFeature = ResourceId<"minecraft:worldgen/configured_feature">;
export const ConfiguredFeature = (id: string): ConfiguredFeature => new ResourceId(id, "minecraft:worldgen/configured_feature");

export type DamageType = ResourceId<"minecraft:damage_type">;
export const DamageType = withMembers(
  (id: string): DamageType => new ResourceId(id, "minecraft:damage_type"),
  DAMAGE_TYPE_IDS,
  (id) => new ResourceId(id, "minecraft:damage_type"),
);

export type Dialog = ResourceId<"minecraft:dialog">;
export const Dialog = (id: string): Dialog => new ResourceId(id, "minecraft:dialog");

export type Dimension = ResourceId<"minecraft:dimension">;
export const Dimension = withMembers(
  (id: string): Dimension => new ResourceId(id, "minecraft:dimension"),
  DIMENSION_IDS,
  (id) => new ResourceId(id, "minecraft:dimension"),
);

export type Enchantment = ResourceId<"minecraft:enchantment">;
export const Enchantment = withMembers(
  (id: string): Enchantment => new ResourceId(id, "minecraft:enchantment"),
  ENCHANTMENT_IDS,
  (id) => new ResourceId(id, "minecraft:enchantment"),
);

export type EntityType = ResourceId<"minecraft:entity_type">;
export const EntityType = withMembers(
  (id: string): EntityType => new ResourceId(id, "minecraft:entity_type"),
  ENTITY_TYPE_IDS,
  (id) => new ResourceId(id, "minecraft:entity_type"),
);

export type FunctionId = ResourceId<"minecraft:function">;
export const FunctionId = (id: string): FunctionId => new ResourceId(id, "minecraft:function");

export type LootModifier = ResourceId<"minecraft:loot_modifier">;
export const LootModifier = (id: string): LootModifier => new ResourceId(id, "minecraft:loot_modifier");

export type LootTable = ResourceId<"minecraft:loot_table">;
export const LootTable = (id: string): LootTable => new ResourceId(id, "minecraft:loot_table");

export type MobEffect = ResourceId<"minecraft:mob_effect">;
export const MobEffect = withMembers(
  (id: string): MobEffect => new ResourceId(id, "minecraft:mob_effect"),
  MOB_EFFECT_IDS,
  (id) => new ResourceId(id, "minecraft:mob_effect"),
);

export type Particle = ResourceId<"minecraft:particle_type">;
export const Particle = withMembers(
  (id: string): Particle => new ResourceId(id, "minecraft:particle_type"),
  PARTICLE_TYPE_IDS,
  (id) => new ResourceId(id, "minecraft:particle_type"),
);

export type PointOfInterestType = ResourceId<"minecraft:point_of_interest_type">;
export const PointOfInterestType = withMembers(
  (id: string): PointOfInterestType => new ResourceId(id, "minecraft:point_of_interest_type"),
  POINT_OF_INTEREST_TYPE_IDS,
  (id) => new ResourceId(id, "minecraft:point_of_interest_type"),
);

export type Recipe = ResourceId<"minecraft:recipe">;
export const Recipe = (id: string): Recipe => new ResourceId(id, "minecraft:recipe");

export type Structure = ResourceId<"minecraft:worldgen/structure">;
export const Structure = withMembers(
  (id: string): Structure => new ResourceId(id, "minecraft:worldgen/structure"),
  WORLDGEN_STRUCTURE_IDS,
  (id) => new ResourceId(id, "minecraft:worldgen/structure"),
);

export type TemplatePool = ResourceId<"minecraft:worldgen/template_pool">;
export const TemplatePool = (id: string): TemplatePool => new ResourceId(id, "minecraft:worldgen/template_pool");

export type TestInstance = ResourceId<"minecraft:test_instance">;
export const TestInstance = (id: string): TestInstance => new ResourceId(id, "minecraft:test_instance");

export type Timeline = ResourceId<"minecraft:timeline">;
export const Timeline = (id: string): Timeline => new ResourceId(id, "minecraft:timeline");

export type WorldClock = ResourceId<"minecraft:world_clock">;
export const WorldClock = (id: string): WorldClock => new ResourceId(id, "minecraft:world_clock");
