// GENERATED by scripts/generate-version.ts -- do not edit by hand.
// Source: misode/mcmeta (1.20.4). Data lives in ./data/1_20_4.json.
import { loadProfile } from "./load";

export const v1_20_4 = loadProfile("1_20_4.json");
