// GENERATED by scripts/generate-version.ts -- do not edit by hand.
// Source: misode/mcmeta (1.21.4). Data lives in ./data/1_21_4.json.
import { loadProfile } from "./load";

export const v1_21_4 = loadProfile("1_21_4.json");
