// GENERATED by scripts/versions.mjs -- do not edit by hand.
// Source: misode/mcmeta (26.1.2). Data fetched into ./data/26_1_2.json at build.
import { loadProfile } from "./load";

export const v26_1_2 = loadProfile("26_1_2.json");
