// GENERATED by scripts/generate-version.ts -- do not edit by hand.
// Source: misode/mcmeta (26.2). Data lives in ./data/26_2.json.
import { loadProfile } from "./load";

export const v26_2 = loadProfile("26_2.json");
