// GENERATED by scripts/versions.mjs -- do not edit by hand.
// Source: misode/mcmeta; each profile's data lives in ./data/<version>.json.
import { loadProfile } from "./load";

export const v1_20_1 = loadProfile("1_20_1.json");
export const v1_20_4 = loadProfile("1_20_4.json");
export const v1_21_4 = loadProfile("1_21_4.json");
export const v26_2 = loadProfile("26_2.json");
export const v26_1_2 = loadProfile("26_1_2.json");
