// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Advancement } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `advancement` */
export class AdvancementNode extends CommandNodeBase {
  readonly type = "advancement";
}

export class AdvancementBuilder extends CommandBuilder<AdvancementNode> {
  grantEverything(targets: Selector): this {
    this.$set(litPart("advancement"), litPart("grant"), argPart(targets), litPart("everything"));
    return this;
  }

  grantFrom(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("grant"), argPart(targets), litPart("from"), argPart(advancement));
    return this;
  }

  grantOnly(targets: Selector, advancement: Advancement, criterion?: string): this {
    this.$set(litPart("advancement"), litPart("grant"), argPart(targets), litPart("only"), argPart(advancement));
    if (criterion !== undefined) this.$append(argPart(criterion));
    return this;
  }

  grantThrough(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("grant"), argPart(targets), litPart("through"), argPart(advancement));
    return this;
  }

  grantUntil(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("grant"), argPart(targets), litPart("until"), argPart(advancement));
    return this;
  }

  revokeEverything(targets: Selector): this {
    this.$set(litPart("advancement"), litPart("revoke"), argPart(targets), litPart("everything"));
    return this;
  }

  revokeFrom(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("revoke"), argPart(targets), litPart("from"), argPart(advancement));
    return this;
  }

  revokeOnly(targets: Selector, advancement: Advancement, criterion?: string): this {
    this.$set(litPart("advancement"), litPart("revoke"), argPart(targets), litPart("only"), argPart(advancement));
    if (criterion !== undefined) this.$append(argPart(criterion));
    return this;
  }

  revokeThrough(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("revoke"), argPart(targets), litPart("through"), argPart(advancement));
    return this;
  }

  revokeUntil(targets: Selector, advancement: Advancement): this {
    this.$set(litPart("advancement"), litPart("revoke"), argPart(targets), litPart("until"), argPart(advancement));
    return this;
  }
}

export class AdvancementHandler extends TreeCommandHandler<AdvancementNode> {
  readonly type: AdvancementNode["type"] = "advancement";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `advancement` - `ctx.advancement()...` */
    advancement(): AdvancementBuilder;
  }
}

FunctionContext.prototype.advancement = function (this: FunctionContext) {
  const node = new AdvancementNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("advancement")];
  node.parts = parts;
  return new AdvancementBuilder(node);
};
