// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Attribute, Id } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `attribute` */
export class AttributeNode extends CommandNodeBase {
  readonly type = "attribute";
}

export class AttributeBuilder extends CommandBuilder<AttributeNode> {
  baseGet(target: Selector, attribute: Attribute, scale?: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("base"), litPart("get"));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  baseReset(target: Selector, attribute: Attribute): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("base"), litPart("reset"));
    return this;
  }

  baseSet(target: Selector, attribute: Attribute, value: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("base"), litPart("set"), argPart(value));
    return this;
  }

  get(target: Selector, attribute: Attribute, scale?: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("get"));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  modifierAddAddMultipliedBase(target: Selector, attribute: Attribute, id: Id, value: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("modifier"), litPart("add"), argPart(id), argPart(value), litPart("add_multiplied_base"));
    return this;
  }

  modifierAddAddMultipliedTotal(target: Selector, attribute: Attribute, id: Id, value: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("modifier"), litPart("add"), argPart(id), argPart(value), litPart("add_multiplied_total"));
    return this;
  }

  modifierAddAddValue(target: Selector, attribute: Attribute, id: Id, value: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("modifier"), litPart("add"), argPart(id), argPart(value), litPart("add_value"));
    return this;
  }

  modifierRemove(target: Selector, attribute: Attribute, id: Id): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("modifier"), litPart("remove"), argPart(id));
    return this;
  }

  modifierValueGet(target: Selector, attribute: Attribute, id: Id, scale?: number): this {
    this.$set(litPart("attribute"), argPart(target), argPart(attribute), litPart("modifier"), litPart("value"), litPart("get"), argPart(id));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }
}

export class AttributeHandler extends TreeCommandHandler<AttributeNode> {
  readonly type: AttributeNode["type"] = "attribute";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `attribute` - `ctx.attribute()...` */
    attribute(): AttributeBuilder;
  }
}

FunctionContext.prototype.attribute = function (this: FunctionContext) {
  const node = new AttributeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("attribute")];
  node.parts = parts;
  return new AttributeBuilder(node);
};
