// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";

/** `ban-ip` */
export class BanIpNode extends CommandNodeBase {
  readonly type = "ban-ip";
}

export class BanIpBuilder extends CommandBuilder<BanIpNode> {

}

export class BanIpHandler extends TreeCommandHandler<BanIpNode> {
  readonly type: BanIpNode["type"] = "ban-ip";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `ban-ip` - `ctx.banIp()...` */
    banIp(target: string, reason?: Message): BanIpBuilder;
  }
}

FunctionContext.prototype.banIp = function (this: FunctionContext, target: string, reason?: Message) {
  const node = new BanIpNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("ban-ip"), argPart(target)];
  if (reason !== undefined) parts.push(argPart(reason));
  node.parts = parts;
  return new BanIpBuilder(node);
};
