// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `ban` */
export class BanNode extends CommandNodeBase {
  readonly type = "ban";
}

export class BanBuilder extends CommandBuilder<BanNode> {

}

export class BanHandler extends TreeCommandHandler<BanNode> {
  readonly type: BanNode["type"] = "ban";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `ban` - `ctx.ban()...` */
    ban(targets: Selector, reason?: Message): BanBuilder;
  }
}

FunctionContext.prototype.ban = function (this: FunctionContext, targets: Selector, reason?: Message) {
  const node = new BanNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("ban"), argPart(targets)];
  if (reason !== undefined) parts.push(argPart(reason));
  node.parts = parts;
  return new BanBuilder(node);
};
