// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `banlist` */
export class BanlistNode extends CommandNodeBase {
  readonly type = "banlist";
}

export class BanlistBuilder extends CommandBuilder<BanlistNode> {
  ips(): this {
    this.$set(litPart("banlist"), litPart("ips"));
    return this;
  }

  players(): this {
    this.$set(litPart("banlist"), litPart("players"));
    return this;
  }
}

export class BanlistHandler extends TreeCommandHandler<BanlistNode> {
  readonly type: BanlistNode["type"] = "banlist";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `banlist` - `ctx.banlist()...` */
    banlist(): BanlistBuilder;
  }
}

FunctionContext.prototype.banlist = function (this: FunctionContext) {
  const node = new BanlistNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("banlist")];
  node.parts = parts;
  return new BanlistBuilder(node);
};
