// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Component, Id } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `bossbar` */
export class BossbarBuilder extends CommandBuilder<TreeCommandNode> {
  add(id: Id, name: Component): this {
    this.$set(litPart("bossbar"), litPart("add"), argPart(id), argPart(name));
    return this;
  }

  getMax(id: Id): this {
    this.$set(litPart("bossbar"), litPart("get"), argPart(id), litPart("max"));
    return this;
  }

  getPlayers(id: Id): this {
    this.$set(litPart("bossbar"), litPart("get"), argPart(id), litPart("players"));
    return this;
  }

  getValue(id: Id): this {
    this.$set(litPart("bossbar"), litPart("get"), argPart(id), litPart("value"));
    return this;
  }

  getVisible(id: Id): this {
    this.$set(litPart("bossbar"), litPart("get"), argPart(id), litPart("visible"));
    return this;
  }

  list(): this {
    this.$set(litPart("bossbar"), litPart("list"));
    return this;
  }

  remove(id: Id): this {
    this.$set(litPart("bossbar"), litPart("remove"), argPart(id));
    return this;
  }

  setColorBlue(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("blue"));
    return this;
  }

  setColorGreen(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("green"));
    return this;
  }

  setColorPink(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("pink"));
    return this;
  }

  setColorPurple(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("purple"));
    return this;
  }

  setColorRed(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("red"));
    return this;
  }

  setColorWhite(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("white"));
    return this;
  }

  setColorYellow(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("color"), litPart("yellow"));
    return this;
  }

  setMax(id: Id, max: number): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("max"), argPart(max));
    return this;
  }

  setName(id: Id, name: Component): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("name"), argPart(name));
    return this;
  }

  setPlayers(id: Id, targets?: Selector): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("players"));
    if (targets !== undefined) this.$append(argPart(targets));
    return this;
  }

  setStyleNotched10(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("style"), litPart("notched_10"));
    return this;
  }

  setStyleNotched12(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("style"), litPart("notched_12"));
    return this;
  }

  setStyleNotched20(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("style"), litPart("notched_20"));
    return this;
  }

  setStyleNotched6(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("style"), litPart("notched_6"));
    return this;
  }

  setStyleProgress(id: Id): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("style"), litPart("progress"));
    return this;
  }

  setValue(id: Id, value: number): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("value"), argPart(value));
    return this;
  }

  setVisible(id: Id, visible: boolean): this {
    this.$set(litPart("bossbar"), litPart("set"), argPart(id), litPart("visible"), argPart(visible));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `bossbar` - `ctx.bossbar()...` */
    bossbar(): BossbarBuilder;
  }
}

FunctionContext.prototype.bossbar = function (this: FunctionContext) {
  const node = new TreeCommandNode("bossbar");
  this.emit(node);
  const parts: CommandPart[] = [litPart("bossbar")];
  node.parts = parts;
  return new BossbarBuilder(node);
};
