// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Item } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `clear` */
export class ClearNode extends CommandNodeBase {
  readonly type = "clear";
}

export class ClearBuilder extends CommandBuilder<ClearNode> {

}

export class ClearHandler extends TreeCommandHandler<ClearNode> {
  readonly type: ClearNode["type"] = "clear";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `clear` - `ctx.clear()...` */
    clear(targets?: Selector, item?: Item, maxCount?: number): ClearBuilder;
  }
}

FunctionContext.prototype.clear = function (this: FunctionContext, targets?: Selector, item?: Item, maxCount?: number) {
  const node = new ClearNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("clear")];
  if (targets !== undefined) parts.push(argPart(targets));
  if (item !== undefined) parts.push(argPart(item));
  if (maxCount !== undefined) parts.push(argPart(maxCount));
  node.parts = parts;
  return new ClearBuilder(node);
};
