// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Block, Dimension, Pos } from "../values";

/** `clone` */
export class CloneBuilder extends CommandBuilder<TreeCommandNode> {
  filtered(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter));
    return this;
  }

  filteredForce(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  filteredMove(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  filteredNormal(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  from(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination));
    return this;
  }

  fromFiltered(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter));
    return this;
  }

  fromFilteredForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  fromFilteredMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  fromFilteredNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  fromMasked(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("masked"));
    return this;
  }

  fromMaskedForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("force"));
    return this;
  }

  fromMaskedMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("move"));
    return this;
  }

  fromMaskedNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("normal"));
    return this;
  }

  fromReplace(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("replace"));
    return this;
  }

  fromReplaceForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("force"));
    return this;
  }

  fromReplaceMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("move"));
    return this;
  }

  fromReplaceNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("normal"));
    return this;
  }

  fromStrict(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"));
    return this;
  }

  fromStrictFiltered(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter));
    return this;
  }

  fromStrictFilteredForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  fromStrictFilteredMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  fromStrictFilteredNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  fromStrictMasked(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"));
    return this;
  }

  fromStrictMaskedForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("force"));
    return this;
  }

  fromStrictMaskedMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("move"));
    return this;
  }

  fromStrictMaskedNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("normal"));
    return this;
  }

  fromStrictReplace(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"));
    return this;
  }

  fromStrictReplaceForce(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("force"));
    return this;
  }

  fromStrictReplaceMove(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("move"));
    return this;
  }

  fromStrictReplaceNormal(sourceDimension: Dimension, begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("normal"));
    return this;
  }

  fromTo(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination));
    return this;
  }

  fromToFiltered(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter));
    return this;
  }

  fromToFilteredForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  fromToFilteredMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  fromToFilteredNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  fromToMasked(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"));
    return this;
  }

  fromToMaskedForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("force"));
    return this;
  }

  fromToMaskedMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("move"));
    return this;
  }

  fromToMaskedNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("normal"));
    return this;
  }

  fromToReplace(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"));
    return this;
  }

  fromToReplaceForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("force"));
    return this;
  }

  fromToReplaceMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("move"));
    return this;
  }

  fromToReplaceNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("normal"));
    return this;
  }

  fromToStrict(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"));
    return this;
  }

  fromToStrictFiltered(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter));
    return this;
  }

  fromToStrictFilteredForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  fromToStrictFilteredMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  fromToStrictFilteredNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  fromToStrictMasked(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"));
    return this;
  }

  fromToStrictMaskedForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("force"));
    return this;
  }

  fromToStrictMaskedMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("move"));
    return this;
  }

  fromToStrictMaskedNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("normal"));
    return this;
  }

  fromToStrictReplace(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"));
    return this;
  }

  fromToStrictReplaceForce(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("force"));
    return this;
  }

  fromToStrictReplaceMove(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("move"));
    return this;
  }

  fromToStrictReplaceNormal(sourceDimension: Dimension, begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), litPart("from"), argPart(sourceDimension), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("normal"));
    return this;
  }

  masked(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("masked"));
    return this;
  }

  maskedForce(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("force"));
    return this;
  }

  maskedMove(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("move"));
    return this;
  }

  maskedNormal(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("masked"), litPart("normal"));
    return this;
  }

  replace(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("replace"));
    return this;
  }

  replaceForce(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("force"));
    return this;
  }

  replaceMove(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("move"));
    return this;
  }

  replaceNormal(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("replace"), litPart("normal"));
    return this;
  }

  strict(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"));
    return this;
  }

  strictFiltered(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter));
    return this;
  }

  strictFilteredForce(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  strictFilteredMove(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  strictFilteredNormal(begin: Pos, end: Pos, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  strictMasked(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"));
    return this;
  }

  strictMaskedForce(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("force"));
    return this;
  }

  strictMaskedMove(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("move"));
    return this;
  }

  strictMaskedNormal(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("masked"), litPart("normal"));
    return this;
  }

  strictReplace(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"));
    return this;
  }

  strictReplaceForce(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("force"));
    return this;
  }

  strictReplaceMove(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("move"));
    return this;
  }

  strictReplaceNormal(begin: Pos, end: Pos, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), argPart(destination), litPart("strict"), litPart("replace"), litPart("normal"));
    return this;
  }

  to(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination));
    return this;
  }

  toFiltered(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter));
    return this;
  }

  toFilteredForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  toFilteredMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  toFilteredNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  toMasked(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"));
    return this;
  }

  toMaskedForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("force"));
    return this;
  }

  toMaskedMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("move"));
    return this;
  }

  toMaskedNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("masked"), litPart("normal"));
    return this;
  }

  toReplace(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"));
    return this;
  }

  toReplaceForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("force"));
    return this;
  }

  toReplaceMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("move"));
    return this;
  }

  toReplaceNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("replace"), litPart("normal"));
    return this;
  }

  toStrict(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"));
    return this;
  }

  toStrictFiltered(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter));
    return this;
  }

  toStrictFilteredForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("force"));
    return this;
  }

  toStrictFilteredMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("move"));
    return this;
  }

  toStrictFilteredNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos, filter: Block): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("filtered"), argPart(filter), litPart("normal"));
    return this;
  }

  toStrictMasked(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"));
    return this;
  }

  toStrictMaskedForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("force"));
    return this;
  }

  toStrictMaskedMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("move"));
    return this;
  }

  toStrictMaskedNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("masked"), litPart("normal"));
    return this;
  }

  toStrictReplace(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"));
    return this;
  }

  toStrictReplaceForce(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("force"));
    return this;
  }

  toStrictReplaceMove(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("move"));
    return this;
  }

  toStrictReplaceNormal(begin: Pos, end: Pos, targetDimension: Dimension, destination: Pos): this {
    this.$set(litPart("clone"), argPart(begin), argPart(end), litPart("to"), argPart(targetDimension), argPart(destination), litPart("strict"), litPart("replace"), litPart("normal"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `clone` - `ctx.clone()...` */
    clone(begin?: Pos, end?: Pos, destination?: Pos): CloneBuilder;
  }
}

FunctionContext.prototype.clone = function (this: FunctionContext, begin?: Pos, end?: Pos, destination?: Pos) {
  const node = new TreeCommandNode("clone");
  this.emit(node);
  const parts: CommandPart[] = [litPart("clone")];
  if (begin !== undefined) parts.push(argPart(begin));
  if (end !== undefined) parts.push(argPart(end));
  if (destination !== undefined) parts.push(argPart(destination));
  node.parts = parts;
  return new CloneBuilder(node);
};
