// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { Effect } from "../ir/line-info";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart, single } from "./base";
import { ContextFloatProvider, ContextIntProvider, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `compute` */
export class ComputeBuilder extends CommandBuilder<TreeCommandNode> {
  blockFloat(computePos: Pos, provider: ContextFloatProvider, scale?: number): this {
    this.$set(litPart("compute"), litPart("block"), argPart(computePos), litPart("float"), argPart(provider));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  blockInteger(computePos: Pos, provider: ContextIntProvider): this {
    this.$set(litPart("compute"), litPart("block"), argPart(computePos), litPart("integer"), argPart(provider));
    return this;
  }

  defaultFloat(provider: ContextFloatProvider, scale?: number): this {
    this.$set(litPart("compute"), litPart("default"), litPart("float"), argPart(provider));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  defaultInteger(provider: ContextIntProvider): this {
    this.$set(litPart("compute"), litPart("default"), litPart("integer"), argPart(provider));
    return this;
  }

  entityFloat(computeTarget: Selector, provider: ContextFloatProvider, scale?: number): this {
    this.$set(litPart("compute"), litPart("entity"), argPart(single(computeTarget, "compute")), litPart("float"), argPart(provider));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  entityInteger(computeTarget: Selector, provider: ContextIntProvider): this {
    this.$set(litPart("compute"), litPart("entity"), argPart(single(computeTarget, "compute")), litPart("integer"), argPart(provider));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `compute` - `ctx.compute()...` */
    compute(): ComputeBuilder;
  }
}

FunctionContext.prototype.compute = function (this: FunctionContext) {
  const node = new TreeCommandNode("compute", { effect: Effect.NONE });
  this.emit(node);
  const parts: CommandPart[] = [litPart("compute")];
  node.parts = parts;
  return new ComputeBuilder(node);
};
