// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { DamageType, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `damage` */
export class DamageBuilder extends CommandBuilder<TreeCommandNode> {
  at(target: Selector, amount: number, damageType: DamageType, location: Pos): this {
    this.$set(litPart("damage"), argPart(target), argPart(amount), argPart(damageType), litPart("at"), argPart(location));
    return this;
  }

  by(target: Selector, amount: number, damageType: DamageType, entity: Selector): this {
    this.$set(litPart("damage"), argPart(target), argPart(amount), argPart(damageType), litPart("by"), argPart(entity));
    return this;
  }

  byFrom(target: Selector, amount: number, damageType: DamageType, entity: Selector, cause: Selector): this {
    this.$set(litPart("damage"), argPart(target), argPart(amount), argPart(damageType), litPart("by"), argPart(entity), litPart("from"), argPart(cause));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `damage` - `ctx.damage()...` */
    damage(target?: Selector, amount?: number, damageType?: DamageType): DamageBuilder;
  }
}

FunctionContext.prototype.damage = function (this: FunctionContext, target?: Selector, amount?: number, damageType?: DamageType) {
  const node = new TreeCommandNode("damage");
  this.emit(node);
  const parts: CommandPart[] = [litPart("damage")];
  if (target !== undefined) parts.push(argPart(target));
  if (amount !== undefined) parts.push(argPart(amount));
  if (damageType !== undefined) parts.push(argPart(damageType));
  node.parts = parts;
  return new DamageBuilder(node);
};
