// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { FunctionId } from "../values";

/** `debug` */
export class DebugNode extends CommandNodeBase {
  readonly type = "debug";
}

export class DebugBuilder extends CommandBuilder<DebugNode> {
  function_(name: FunctionId): this {
    this.$set(litPart("debug"), litPart("function"), argPart(name));
    return this;
  }

  start(): this {
    this.$set(litPart("debug"), litPart("start"));
    return this;
  }

  stop(): this {
    this.$set(litPart("debug"), litPart("stop"));
    return this;
  }
}

export class DebugHandler extends TreeCommandHandler<DebugNode> {
  readonly type: DebugNode["type"] = "debug";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `debug` - `ctx.debug()...` */
    debug(): DebugBuilder;
  }
}

FunctionContext.prototype.debug = function (this: FunctionContext) {
  const node = new DebugNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("debug")];
  node.parts = parts;
  return new DebugBuilder(node);
};
