// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Gamemode } from "../values";

/** `defaultgamemode` */
export class DefaultgamemodeNode extends CommandNodeBase {
  readonly type = "defaultgamemode";
}

export class DefaultgamemodeBuilder extends CommandBuilder<DefaultgamemodeNode> {

}

export class DefaultgamemodeHandler extends TreeCommandHandler<DefaultgamemodeNode> {
  readonly type: DefaultgamemodeNode["type"] = "defaultgamemode";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `defaultgamemode` - `ctx.defaultgamemode()...` */
    defaultgamemode(gamemode: Gamemode): DefaultgamemodeBuilder;
  }
}

FunctionContext.prototype.defaultgamemode = function (this: FunctionContext, gamemode: Gamemode) {
  const node = new DefaultgamemodeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("defaultgamemode"), argPart(gamemode)];
  node.parts = parts;
  return new DefaultgamemodeBuilder(node);
};
