// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Gamemode } from "../values";

/** `defaultgamemode` */
export class DefaultgamemodeBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `defaultgamemode` - `ctx.defaultgamemode()...` */
    defaultgamemode(gamemode: Gamemode): DefaultgamemodeBuilder;
  }
}

FunctionContext.prototype.defaultgamemode = function (this: FunctionContext, gamemode: Gamemode) {
  const node = new TreeCommandNode("defaultgamemode");
  this.emit(node);
  const parts: CommandPart[] = [litPart("defaultgamemode"), argPart(gamemode)];
  node.parts = parts;
  return new DefaultgamemodeBuilder(node);
};
