// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `deop` */
export class DeopNode extends CommandNodeBase {
  readonly type = "deop";
}

export class DeopBuilder extends CommandBuilder<DeopNode> {

}

export class DeopHandler extends TreeCommandHandler<DeopNode> {
  readonly type: DeopNode["type"] = "deop";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `deop` - `ctx.deop()...` */
    deop(targets: Selector): DeopBuilder;
  }
}

FunctionContext.prototype.deop = function (this: FunctionContext, targets: Selector) {
  const node = new DeopNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("deop"), argPart(targets)];
  node.parts = parts;
  return new DeopBuilder(node);
};
