// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Dialog } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `dialog` */
export class DialogBuilder extends CommandBuilder<TreeCommandNode> {
  clear(targets: Selector): this {
    this.$set(litPart("dialog"), litPart("clear"), argPart(targets));
    return this;
  }

  show(targets: Selector, dialog: Dialog): this {
    this.$set(litPart("dialog"), litPart("show"), argPart(targets), argPart(dialog));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `dialog` - `ctx.dialog()...` */
    dialog(): DialogBuilder;
  }
}

FunctionContext.prototype.dialog = function (this: FunctionContext) {
  const node = new TreeCommandNode("dialog");
  this.emit(node);
  const parts: CommandPart[] = [litPart("dialog")];
  node.parts = parts;
  return new DialogBuilder(node);
};
