// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `difficulty` */
export class DifficultyNode extends CommandNodeBase {
  readonly type = "difficulty";
}

export class DifficultyBuilder extends CommandBuilder<DifficultyNode> {
  easy(): this {
    this.$set(litPart("difficulty"), litPart("easy"));
    return this;
  }

  hard(): this {
    this.$set(litPart("difficulty"), litPart("hard"));
    return this;
  }

  normal(): this {
    this.$set(litPart("difficulty"), litPart("normal"));
    return this;
  }

  peaceful(): this {
    this.$set(litPart("difficulty"), litPart("peaceful"));
    return this;
  }
}

export class DifficultyHandler extends TreeCommandHandler<DifficultyNode> {
  readonly type: DifficultyNode["type"] = "difficulty";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `difficulty` - `ctx.difficulty()...` */
    difficulty(): DifficultyBuilder;
  }
}

FunctionContext.prototype.difficulty = function (this: FunctionContext) {
  const node = new DifficultyNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("difficulty")];
  node.parts = parts;
  return new DifficultyBuilder(node);
};
