// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `difficulty` */
export class DifficultyBuilder extends CommandBuilder<TreeCommandNode> {
  easy(): this {
    this.$set(litPart("difficulty"), litPart("easy"));
    return this;
  }

  hard(): this {
    this.$set(litPart("difficulty"), litPart("hard"));
    return this;
  }

  normal(): this {
    this.$set(litPart("difficulty"), litPart("normal"));
    return this;
  }

  peaceful(): this {
    this.$set(litPart("difficulty"), litPart("peaceful"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `difficulty` - `ctx.difficulty()...` */
    difficulty(): DifficultyBuilder;
  }
}

FunctionContext.prototype.difficulty = function (this: FunctionContext) {
  const node = new TreeCommandNode("difficulty");
  this.emit(node);
  const parts: CommandPart[] = [litPart("difficulty")];
  node.parts = parts;
  return new DifficultyBuilder(node);
};
