// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { MobEffect } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `effect` */
export class EffectNode extends CommandNodeBase {
  readonly type = "effect";
}

export class EffectBuilder extends CommandBuilder<EffectNode> {
  clear(targets?: Selector, effect?: MobEffect): this {
    this.$set(litPart("effect"), litPart("clear"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (effect !== undefined) this.$append(argPart(effect));
    return this;
  }

  give(targets: Selector, effect: MobEffect, seconds?: number, amplifier?: number, hideParticles?: boolean): this {
    this.$set(litPart("effect"), litPart("give"), argPart(targets), argPart(effect));
    if (seconds !== undefined) this.$append(argPart(seconds));
    if (amplifier !== undefined) this.$append(argPart(amplifier));
    if (hideParticles !== undefined) this.$append(argPart(hideParticles));
    return this;
  }

  giveInfinite(targets: Selector, effect: MobEffect, amplifier?: number, hideParticles?: boolean): this {
    this.$set(litPart("effect"), litPart("give"), argPart(targets), argPart(effect), litPart("infinite"));
    if (amplifier !== undefined) this.$append(argPart(amplifier));
    if (hideParticles !== undefined) this.$append(argPart(hideParticles));
    return this;
  }
}

export class EffectHandler extends TreeCommandHandler<EffectNode> {
  readonly type: EffectNode["type"] = "effect";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `effect` - `ctx.effect()...` */
    effect(): EffectBuilder;
  }
}

FunctionContext.prototype.effect = function (this: FunctionContext) {
  const node = new EffectNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("effect")];
  node.parts = parts;
  return new EffectBuilder(node);
};
