// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Enchantment } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `enchant` */
export class EnchantBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `enchant` - `ctx.enchant()...` */
    enchant(targets: Selector, enchantment: Enchantment, level?: number): EnchantBuilder;
  }
}

FunctionContext.prototype.enchant = function (this: FunctionContext, targets: Selector, enchantment: Enchantment, level?: number) {
  const node = new TreeCommandNode("enchant");
  this.emit(node);
  const parts: CommandPart[] = [litPart("enchant"), argPart(targets), argPart(enchantment)];
  if (level !== undefined) parts.push(argPart(level));
  node.parts = parts;
  return new EnchantBuilder(node);
};
