// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `experience` */
export class ExperienceNode extends CommandNodeBase {
  readonly type = "experience";
}

export class ExperienceBuilder extends CommandBuilder<ExperienceNode> {
  add(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("add"), argPart(target), argPart(amount));
    return this;
  }

  addLevels(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("add"), argPart(target), argPart(amount), litPart("levels"));
    return this;
  }

  addPoints(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("add"), argPart(target), argPart(amount), litPart("points"));
    return this;
  }

  queryLevels(target: Selector): this {
    this.$set(litPart("experience"), litPart("query"), argPart(target), litPart("levels"));
    return this;
  }

  queryPoints(target: Selector): this {
    this.$set(litPart("experience"), litPart("query"), argPart(target), litPart("points"));
    return this;
  }

  set(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("set"), argPart(target), argPart(amount));
    return this;
  }

  setLevels(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("set"), argPart(target), argPart(amount), litPart("levels"));
    return this;
  }

  setPoints(target: Selector, amount: number): this {
    this.$set(litPart("experience"), litPart("set"), argPart(target), argPart(amount), litPart("points"));
    return this;
  }
}

export class ExperienceHandler extends TreeCommandHandler<ExperienceNode> {
  readonly type: ExperienceNode["type"] = "experience";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `experience` - `ctx.experience()...` */
    experience(): ExperienceBuilder;
  }
}

FunctionContext.prototype.experience = function (this: FunctionContext) {
  const node = new ExperienceNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("experience")];
  node.parts = parts;
  return new ExperienceBuilder(node);
};
