// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Uuid } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `fetchprofile` */
export class FetchprofileNode extends CommandNodeBase {
  readonly type = "fetchprofile";
}

export class FetchprofileBuilder extends CommandBuilder<FetchprofileNode> {
  entity(entity: Selector): this {
    this.$set(litPart("fetchprofile"), litPart("entity"), argPart(entity));
    return this;
  }

  id(id: Uuid): this {
    this.$set(litPart("fetchprofile"), litPart("id"), argPart(id));
    return this;
  }

  name(name: string): this {
    this.$set(litPart("fetchprofile"), litPart("name"), argPart(name));
    return this;
  }
}

export class FetchprofileHandler extends TreeCommandHandler<FetchprofileNode> {
  readonly type: FetchprofileNode["type"] = "fetchprofile";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `fetchprofile` - `ctx.fetchprofile()...` */
    fetchprofile(): FetchprofileBuilder;
  }
}

FunctionContext.prototype.fetchprofile = function (this: FunctionContext) {
  const node = new FetchprofileNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("fetchprofile")];
  node.parts = parts;
  return new FetchprofileBuilder(node);
};
