// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Block, Pos } from "../values";

/** `fill` */
export class FillNode extends CommandNodeBase {
  readonly type = "fill";
}

export class FillBuilder extends CommandBuilder<FillNode> {
  destroy(from: Pos, to: Pos, block: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("destroy"));
    return this;
  }

  hollow(from: Pos, to: Pos, block: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("hollow"));
    return this;
  }

  keep(from: Pos, to: Pos, block: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("keep"));
    return this;
  }

  outline(from: Pos, to: Pos, block: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("outline"));
    return this;
  }

  replace(from: Pos, to: Pos, block: Block, filter?: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("replace"));
    if (filter !== undefined) this.$append(argPart(filter));
    return this;
  }

  replaceDestroy(from: Pos, to: Pos, block: Block, filter: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("replace"), argPart(filter), litPart("destroy"));
    return this;
  }

  replaceHollow(from: Pos, to: Pos, block: Block, filter: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("replace"), argPart(filter), litPart("hollow"));
    return this;
  }

  replaceOutline(from: Pos, to: Pos, block: Block, filter: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("replace"), argPart(filter), litPart("outline"));
    return this;
  }

  replaceStrict(from: Pos, to: Pos, block: Block, filter: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("replace"), argPart(filter), litPart("strict"));
    return this;
  }

  strict(from: Pos, to: Pos, block: Block): this {
    this.$set(litPart("fill"), argPart(from), argPart(to), argPart(block), litPart("strict"));
    return this;
  }
}

export class FillHandler extends TreeCommandHandler<FillNode> {
  readonly type: FillNode["type"] = "fill";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `fill` - `ctx.fill()...` */
    fill(from?: Pos, to?: Pos, block?: Block): FillBuilder;
  }
}

FunctionContext.prototype.fill = function (this: FunctionContext, from?: Pos, to?: Pos, block?: Block) {
  const node = new FillNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("fill")];
  if (from !== undefined) parts.push(argPart(from));
  if (to !== undefined) parts.push(argPart(to));
  if (block !== undefined) parts.push(argPart(block));
  node.parts = parts;
  return new FillBuilder(node);
};
