// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Biome, Pos } from "../values";

/** `fillbiome` */
export class FillbiomeNode extends CommandNodeBase {
  readonly type = "fillbiome";
}

export class FillbiomeBuilder extends CommandBuilder<FillbiomeNode> {
  replace(from: Pos, to: Pos, biome: Biome, filter: Biome): this {
    this.$set(litPart("fillbiome"), argPart(from), argPart(to), argPart(biome), litPart("replace"), argPart(filter));
    return this;
  }
}

export class FillbiomeHandler extends TreeCommandHandler<FillbiomeNode> {
  readonly type: FillbiomeNode["type"] = "fillbiome";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `fillbiome` - `ctx.fillbiome()...` */
    fillbiome(from?: Pos, to?: Pos, biome?: Biome): FillbiomeBuilder;
  }
}

FunctionContext.prototype.fillbiome = function (this: FunctionContext, from?: Pos, to?: Pos, biome?: Biome) {
  const node = new FillbiomeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("fillbiome")];
  if (from !== undefined) parts.push(argPart(from));
  if (to !== undefined) parts.push(argPart(to));
  if (biome !== undefined) parts.push(argPart(biome));
  node.parts = parts;
  return new FillbiomeBuilder(node);
};
