// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Biome, Pos } from "../values";

/** `fillbiome` */
export class FillbiomeBuilder extends CommandBuilder<TreeCommandNode> {
  replace(from: Pos, to: Pos, biome: Biome, filter: Biome): this {
    this.$set(litPart("fillbiome"), argPart(from), argPart(to), argPart(biome), litPart("replace"), argPart(filter));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `fillbiome` - `ctx.fillbiome()...` */
    fillbiome(from?: Pos, to?: Pos, biome?: Biome): FillbiomeBuilder;
  }
}

FunctionContext.prototype.fillbiome = function (this: FunctionContext, from?: Pos, to?: Pos, biome?: Biome) {
  const node = new TreeCommandNode("fillbiome");
  this.emit(node);
  const parts: CommandPart[] = [litPart("fillbiome")];
  if (from !== undefined) parts.push(argPart(from));
  if (to !== undefined) parts.push(argPart(to));
  if (biome !== undefined) parts.push(argPart(biome));
  node.parts = parts;
  return new FillbiomeBuilder(node);
};
