// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos } from "../values";

/** `forceload` */
export class ForceloadNode extends CommandNodeBase {
  readonly type = "forceload";
}

export class ForceloadBuilder extends CommandBuilder<ForceloadNode> {
  add(from: Pos, to?: Pos): this {
    this.$set(litPart("forceload"), litPart("add"), argPart(from));
    if (to !== undefined) this.$append(argPart(to));
    return this;
  }

  query(pos?: Pos): this {
    this.$set(litPart("forceload"), litPart("query"));
    if (pos !== undefined) this.$append(argPart(pos));
    return this;
  }

  remove(from: Pos, to?: Pos): this {
    this.$set(litPart("forceload"), litPart("remove"), argPart(from));
    if (to !== undefined) this.$append(argPart(to));
    return this;
  }

  removeAll(): this {
    this.$set(litPart("forceload"), litPart("remove"), litPart("all"));
    return this;
  }
}

export class ForceloadHandler extends TreeCommandHandler<ForceloadNode> {
  readonly type: ForceloadNode["type"] = "forceload";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `forceload` - `ctx.forceload()...` */
    forceload(): ForceloadBuilder;
  }
}

FunctionContext.prototype.forceload = function (this: FunctionContext) {
  const node = new ForceloadNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("forceload")];
  node.parts = parts;
  return new ForceloadBuilder(node);
};
