// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `gamerule` */
export class GameruleBuilder extends CommandBuilder<TreeCommandNode> {
  advanceTime(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("advance_time"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  advanceWeather(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("advance_weather"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  allowEnteringNetherUsingPortals(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("allow_entering_nether_using_portals"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  blockDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("block_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  blockExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("block_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  commandBlockOutput(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("command_block_output"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  commandBlocksWork(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("command_blocks_work"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  drowningDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("drowning_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  elytraMovementCheck(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("elytra_movement_check"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  enderPearlsVanishOnDeath(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("ender_pearls_vanish_on_death"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  entityDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("entity_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  fallDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("fall_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  fireDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("fire_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  fireSpreadRadiusAroundPlayer(value?: number): this {
    this.$set(litPart("gamerule"), litPart("fire_spread_radius_around_player"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  forgiveDeadPlayers(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("forgive_dead_players"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  freezeDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("freeze_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  globalSoundEvents(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("global_sound_events"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  immediateRespawn(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("immediate_respawn"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  keepInventory(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("keep_inventory"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  lavaSourceConversion(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("lava_source_conversion"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  limitedCrafting(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("limited_crafting"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  locatorBar(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("locator_bar"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  logAdminCommands(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("log_admin_commands"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxBlockModifications(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_block_modifications"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxCommandForks(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_command_forks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxCommandSequenceLength(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_command_sequence_length"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxEntityCramming(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_entity_cramming"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxMinecartSpeed(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_minecart_speed"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  maxSnowAccumulationHeight(value?: number): this {
    this.$set(litPart("gamerule"), litPart("max_snow_accumulation_height"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftAdvanceTime(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:advance_time"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftAdvanceWeather(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:advance_weather"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftAllowEnteringNetherUsingPortals(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:allow_entering_nether_using_portals"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftBlockDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:block_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftBlockExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:block_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftCommandBlockOutput(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:command_block_output"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftCommandBlocksWork(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:command_blocks_work"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftDrowningDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:drowning_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftElytraMovementCheck(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:elytra_movement_check"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftEnderPearlsVanishOnDeath(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:ender_pearls_vanish_on_death"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftEntityDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:entity_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftFallDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:fall_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftFireDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:fire_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftFireSpreadRadiusAroundPlayer(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:fire_spread_radius_around_player"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftForgiveDeadPlayers(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:forgive_dead_players"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftFreezeDamage(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:freeze_damage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftGlobalSoundEvents(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:global_sound_events"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftImmediateRespawn(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:immediate_respawn"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftKeepInventory(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:keep_inventory"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftLavaSourceConversion(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:lava_source_conversion"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftLimitedCrafting(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:limited_crafting"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftLocatorBar(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:locator_bar"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftLogAdminCommands(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:log_admin_commands"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxBlockModifications(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_block_modifications"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxCommandForks(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_command_forks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxCommandSequenceLength(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_command_sequence_length"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxEntityCramming(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_entity_cramming"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxMinecartSpeed(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_minecart_speed"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMaxSnowAccumulationHeight(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:max_snow_accumulation_height"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMobDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:mob_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMobExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:mob_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftMobGriefing(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:mob_griefing"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftNaturalHealthRegeneration(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:natural_health_regeneration"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftPlayerMovementCheck(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:player_movement_check"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftPlayersNetherPortalCreativeDelay(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:players_nether_portal_creative_delay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftPlayersNetherPortalDefaultDelay(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:players_nether_portal_default_delay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftPlayersSleepingPercentage(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:players_sleeping_percentage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftProjectilesCanBreakBlocks(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:projectiles_can_break_blocks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftPvp(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:pvp"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftRaids(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:raids"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftRandomTickSpeed(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:random_tick_speed"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftReducedDebugInfo(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:reduced_debug_info"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftRespawnRadius(value?: number): this {
    this.$set(litPart("gamerule"), litPart("minecraft:respawn_radius"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSendCommandFeedback(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:send_command_feedback"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftShowAdvancementMessages(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:show_advancement_messages"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftShowDeathMessages(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:show_death_messages"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnerBlocksWork(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawner_blocks_work"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnMobs(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_mobs"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnMonsters(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_monsters"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnPatrols(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_patrols"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnPhantoms(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_phantoms"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnWanderingTraders(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_wandering_traders"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpawnWardens(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spawn_wardens"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpectatorsGenerateChunks(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spectators_generate_chunks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftSpreadVines(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:spread_vines"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftTntExplodes(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:tnt_explodes"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftTntExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:tnt_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftUniversalAnger(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:universal_anger"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  minecraftWaterSourceConversion(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("minecraft:water_source_conversion"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  mobDrops(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("mob_drops"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  mobExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("mob_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  mobGriefing(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("mob_griefing"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  naturalHealthRegeneration(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("natural_health_regeneration"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  playerMovementCheck(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("player_movement_check"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  playersNetherPortalCreativeDelay(value?: number): this {
    this.$set(litPart("gamerule"), litPart("players_nether_portal_creative_delay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  playersNetherPortalDefaultDelay(value?: number): this {
    this.$set(litPart("gamerule"), litPart("players_nether_portal_default_delay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  playersSleepingPercentage(value?: number): this {
    this.$set(litPart("gamerule"), litPart("players_sleeping_percentage"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  projectilesCanBreakBlocks(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("projectiles_can_break_blocks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  pvp(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("pvp"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  raids(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("raids"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  randomTickSpeed(value?: number): this {
    this.$set(litPart("gamerule"), litPart("random_tick_speed"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  reducedDebugInfo(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("reduced_debug_info"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  respawnRadius(value?: number): this {
    this.$set(litPart("gamerule"), litPart("respawn_radius"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  sendCommandFeedback(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("send_command_feedback"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  showAdvancementMessages(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("show_advancement_messages"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  showDeathMessages(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("show_death_messages"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnerBlocksWork(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawner_blocks_work"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnMobs(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_mobs"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnMonsters(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_monsters"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnPatrols(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_patrols"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnPhantoms(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_phantoms"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnWanderingTraders(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_wandering_traders"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spawnWardens(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spawn_wardens"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spectatorsGenerateChunks(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spectators_generate_chunks"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  spreadVines(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("spread_vines"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  tntExplodes(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("tnt_explodes"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  tntExplosionDropDecay(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("tnt_explosion_drop_decay"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  universalAnger(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("universal_anger"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }

  waterSourceConversion(value?: boolean): this {
    this.$set(litPart("gamerule"), litPart("water_source_conversion"));
    if (value !== undefined) this.$append(argPart(value));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `gamerule` - `ctx.gamerule()...` */
    gamerule(): GameruleBuilder;
  }
}

FunctionContext.prototype.gamerule = function (this: FunctionContext) {
  const node = new TreeCommandNode("gamerule");
  this.emit(node);
  const parts: CommandPart[] = [litPart("gamerule")];
  node.parts = parts;
  return new GameruleBuilder(node);
};
