// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Gamemode } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `gamemode` */
export class GamemodeNode extends CommandNodeBase {
  readonly type = "gamemode";
}

export class GamemodeBuilder extends CommandBuilder<GamemodeNode> {

}

export class GamemodeHandler extends TreeCommandHandler<GamemodeNode> {
  readonly type: GamemodeNode["type"] = "gamemode";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `gamemode` - `ctx.gamemode()...` */
    gamemode(gamemode: Gamemode, target?: Selector): GamemodeBuilder;
  }
}

FunctionContext.prototype.gamemode = function (this: FunctionContext, gamemode: Gamemode, target?: Selector) {
  const node = new GamemodeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("gamemode"), argPart(gamemode)];
  if (target !== undefined) parts.push(argPart(target));
  node.parts = parts;
  return new GamemodeBuilder(node);
};
