// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Gamemode } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `gamemode` */
export class GamemodeBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `gamemode` - `ctx.gamemode()...` */
    gamemode(gamemode: Gamemode, target?: Selector): GamemodeBuilder;
  }
}

FunctionContext.prototype.gamemode = function (this: FunctionContext, gamemode: Gamemode, target?: Selector) {
  const node = new TreeCommandNode("gamemode");
  this.emit(node);
  const parts: CommandPart[] = [litPart("gamemode"), argPart(gamemode)];
  if (target !== undefined) parts.push(argPart(target));
  node.parts = parts;
  return new GamemodeBuilder(node);
};
