// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `help` */
export class HelpNode extends CommandNodeBase {
  readonly type = "help";
}

export class HelpBuilder extends CommandBuilder<HelpNode> {

}

export class HelpHandler extends TreeCommandHandler<HelpNode> {
  readonly type: HelpNode["type"] = "help";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `help` - `ctx.help()...` */
    help(command?: string): HelpBuilder;
  }
}

FunctionContext.prototype.help = function (this: FunctionContext, command?: string) {
  const node = new HelpNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("help")];
  if (command !== undefined) parts.push(argPart(command));
  node.parts = parts;
  return new HelpBuilder(node);
};
