// Command barrel. Importing each file installs its `ctx.<cmd>()`.
// Mostly GENERATED by scripts/gen-commands.mjs; add hand-written commands to HAND_REFINED
// there.
import { CommandHandler } from "../ir/commandhandler";
import { SayCommand } from "./saycommand";
import { ScoreboardCommand } from "./scoreboard";
import { ScoreExprCommand } from "./score-expr";
import { TellrawCommand } from "./tellraw";
import { PlayerGiveCommand } from "./give";
import { TriggerCommand } from "./trigger";
import { RandomCommand } from "./random";
import { FunctionCommand } from "./function";
import { FunctionTagCallCommand } from "./function";
import { MacroCallCommand } from "./function";
import { SelectorCommand } from "./selector";
import { DataOpCommand } from "./data_op";
import { IfHandler } from "./if";
import { ExecuteAsHandler } from "./execute_as";
import { ExecuteHandler } from "./execute";
import { ReturnRunHandler } from "./execute";
import { EntityGuardHandler } from "./entity_guard";
import { NearGuardHandler } from "./near_guard";
import { NativeCallHandler } from "./native";
import { LoopHandler } from "./loop";
import { DataHandler } from "./data";
import { SetblockHandler } from "./setblock";

export * from "./advancement";
export * from "./attribute";
export * from "./bossbar";
export * from "./clear";
export * from "./clone";
export * from "./compute";
export * from "./damage";
export * from "./data";
export * from "./datapack";
export * from "./defaultgamemode";
export * from "./dialog";
export * from "./difficulty";
export * from "./effect";
export * from "./enchant";
export * from "./experience";
export * from "./fetchprofile";
export * from "./fill";
export * from "./fillbiome";
export * from "./forceload";
export * from "./gamemode";
export * from "./gamerule";
export * from "./item";
export * from "./kill";
export * from "./locate";
export * from "./loot";
export * from "./particle";
export * from "./place";
export * from "./playsound";
export * from "./posteffect";
export * from "./recipe";
export * from "./reload";
export * from "./return";
export * from "./ride";
export * from "./rotate";
export * from "./schedule";
export * from "./setblock";
export * from "./setworldspawn";
export * from "./spawnpoint";
export * from "./spreadplayers";
export * from "./stopsound";
export * from "./stopwatch";
export * from "./summon";
export * from "./swing";
export * from "./tag";
export * from "./team";
export * from "./teleport";
export * from "./test";
export * from "./tick";
export * from "./time";
export * from "./title";
export * from "./waypoint";
export * from "./weather";
export * from "./worldborder";
// Re-export the sugar command modules. Without this, their `declare module` augmentations
// (ctx.if, ctx.whenEntity, score ops…) drop out of the .d.ts and other packages can't see
// them.
export * from "./saycommand";
export * from "./scoreboard";
export * from "./score-expr";
export * from "./tellraw";
export * from "./give";
export * from "./trigger";
export * from "./random";
export * from "./function";
export * from "./selector";
export * from "./data_op";
export * from "./if";
export * from "./execute_as";
export * from "./execute";
export * from "./entity_guard";
export * from "./near_guard";
export * from "./native";
export * from "./loop";
export * from "./local";
export * from "./ref";

/**
 * Handlers for nodes that need custom lowering. Generated commands all use
 * `TreeCommandHandler`.
 *
 * A function, not a top-level array, because some handlers import codegen, which imports
 * this
 * barrel; building them at load time hits the cycle.
 */
export function createCommandHandlers(): CommandHandler[] {
  return [
    new SayCommand(),
    new ScoreboardCommand(),
    new ScoreExprCommand(),
    new TellrawCommand(),
    new PlayerGiveCommand(),
    new TriggerCommand(),
    new RandomCommand(),
    new FunctionCommand(),
    new FunctionTagCallCommand(),
    new MacroCallCommand(),
    new SelectorCommand(),
    new DataOpCommand(),
    new IfHandler(),
    new ExecuteAsHandler(),
    new ExecuteHandler(),
    new ReturnRunHandler(),
    new EntityGuardHandler(),
    new NearGuardHandler(),
    new NativeCallHandler(),
    new LoopHandler(),
    new DataHandler(),
    new SetblockHandler(),
  ];
}
