// Command barrel. Importing each command file runs its
// `FunctionContext.prototype.<cmd> = ...` augmentation, so `ctx.<cmd>()`
// exists once this module is loaded. (Mostly GENERATED by scripts/gen-commands.mjs;
// the handler list below is regenerated, so add hand-written commands to
// HAND_REFINED in the script rather than editing this file.)
import { CommandHandler } from "../ir/commandhandler";
import { SayCommand } from "./saycommand";
import { ScoreboardCommand } from "./scoreboard";
import { TellrawCommand } from "./tellraw";
import { PlayerGiveCommand } from "./give";
import { TriggerCommand } from "./trigger";
import { RandomCommand } from "./random";
import { FunctionCommand } from "./function";
import { FunctionTagCallCommand } from "./function";
import { SelectorCommand } from "./selector";
import { DataOpCommand } from "./data_op";
import { IfHandler } from "./if";
import { ExecuteAsHandler } from "./execute_as";
import { ExecuteHandler } from "./execute";
import { ReturnRunHandler } from "./execute";
import { EntityGuardHandler } from "./entity_guard";
import { NearGuardHandler } from "./near_guard";
import { NativeCallHandler } from "./native";
import { DataHandler } from "./data";
import { SetblockHandler } from "./setblock";

export * from "./advancement";
export * from "./attribute";
export * from "./bossbar";
export * from "./clear";
export * from "./clone";
export * from "./damage";
export * from "./data";
export * from "./datapack";
export * from "./defaultgamemode";
export * from "./dialog";
export * from "./difficulty";
export * from "./effect";
export * from "./enchant";
export * from "./experience";
export * from "./fetchprofile";
export * from "./fill";
export * from "./fillbiome";
export * from "./forceload";
export * from "./gamemode";
export * from "./gamerule";
export * from "./item";
export * from "./kill";
export * from "./locate";
export * from "./loot";
export * from "./particle";
export * from "./place";
export * from "./playsound";
export * from "./recipe";
export * from "./reload";
export * from "./return";
export * from "./ride";
export * from "./rotate";
export * from "./schedule";
export * from "./setblock";
export * from "./setworldspawn";
export * from "./spawnpoint";
export * from "./spreadplayers";
export * from "./stopsound";
export * from "./stopwatch";
export * from "./summon";
export * from "./swing";
export * from "./tag";
export * from "./team";
export * from "./teleport";
export * from "./test";
export * from "./tick";
export * from "./time";
export * from "./title";
export * from "./waypoint";
export * from "./weather";
export * from "./worldborder";
// Re-export the sugar/semantic command modules too. The value imports above are
// elided from the emitted .d.ts (they're only used to `new` the handlers), which
// would drop these files - and their `declare module "../frontend/context"`
// prototype augmentations (ctx.if, ctx.whenEntity, ctx.whenPlayerNear, score ops,
// …) - from the published types, so cross-package consumers wouldn't see them.
// export * keeps the files referenced so the augmentations reach consumers.
export * from "./saycommand";
export * from "./scoreboard";
export * from "./tellraw";
export * from "./give";
export * from "./trigger";
export * from "./random";
export * from "./function";
export * from "./selector";
export * from "./data_op";
export * from "./if";
export * from "./execute_as";
export * from "./execute";
export * from "./entity_guard";
export * from "./near_guard";
export * from "./native";

/**
 * Handlers for the nodes that need bespoke lowering. Every *generated* command
 * emits a plain `TreeCommandNode`, which the dispatcher renders with the shared
 * `TreeCommandHandler` - so there is no per-command handler here.
 *
 * Built lazily (a function, not a top-level array) because some sugar handlers
 * import codegen, which imports this barrel -- constructing them at load time
 * would hit the cycle before those classes are initialised.
 */
export function createCommandHandlers(): CommandHandler[] {
  return [
    new SayCommand(),
    new ScoreboardCommand(),
    new TellrawCommand(),
    new PlayerGiveCommand(),
    new TriggerCommand(),
    new RandomCommand(),
    new FunctionCommand(),
    new FunctionTagCallCommand(),
    new SelectorCommand(),
    new DataOpCommand(),
    new IfHandler(),
    new ExecuteAsHandler(),
    new ExecuteHandler(),
    new ReturnRunHandler(),
    new EntityGuardHandler(),
    new NearGuardHandler(),
    new NativeCallHandler(),
    new DataHandler(),
    new SetblockHandler(),
  ];
}
