// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Item, ItemSlot, LootModifier, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `item` */
export class ItemNode extends CommandNodeBase {
  readonly type = "item";
}

export class ItemBuilder extends CommandBuilder<ItemNode> {
  modifyBlock(pos: Pos, slot: ItemSlot, modifier: LootModifier): this {
    this.$set(litPart("item"), litPart("modify"), litPart("block"), argPart(pos), argPart(slot), argPart(modifier));
    return this;
  }

  modifyEntity(targets: Selector, slot: ItemSlot, modifier: LootModifier): this {
    this.$set(litPart("item"), litPart("modify"), litPart("entity"), argPart(targets), argPart(slot), argPart(modifier));
    return this;
  }

  replaceBlockFromBlock(pos: Pos, slot: ItemSlot, source: Pos, sourceSlot: ItemSlot, modifier?: LootModifier): this {
    this.$set(litPart("item"), litPart("replace"), litPart("block"), argPart(pos), argPart(slot), litPart("from"), litPart("block"), argPart(source), argPart(sourceSlot));
    if (modifier !== undefined) this.$append(argPart(modifier));
    return this;
  }

  replaceBlockFromEntity(pos: Pos, slot: ItemSlot, source: Selector, sourceSlot: ItemSlot, modifier?: LootModifier): this {
    this.$set(litPart("item"), litPart("replace"), litPart("block"), argPart(pos), argPart(slot), litPart("from"), litPart("entity"), argPart(source), argPart(sourceSlot));
    if (modifier !== undefined) this.$append(argPart(modifier));
    return this;
  }

  replaceBlockWith(pos: Pos, slot: ItemSlot, item: Item, count?: number): this {
    this.$set(litPart("item"), litPart("replace"), litPart("block"), argPart(pos), argPart(slot), litPart("with"), argPart(item));
    if (count !== undefined) this.$append(argPart(count));
    return this;
  }

  replaceEntityFromBlock(targets: Selector, slot: ItemSlot, source: Pos, sourceSlot: ItemSlot, modifier?: LootModifier): this {
    this.$set(litPart("item"), litPart("replace"), litPart("entity"), argPart(targets), argPart(slot), litPart("from"), litPart("block"), argPart(source), argPart(sourceSlot));
    if (modifier !== undefined) this.$append(argPart(modifier));
    return this;
  }

  replaceEntityFromEntity(targets: Selector, slot: ItemSlot, source: Selector, sourceSlot: ItemSlot, modifier?: LootModifier): this {
    this.$set(litPart("item"), litPart("replace"), litPart("entity"), argPart(targets), argPart(slot), litPart("from"), litPart("entity"), argPart(source), argPart(sourceSlot));
    if (modifier !== undefined) this.$append(argPart(modifier));
    return this;
  }

  replaceEntityWith(targets: Selector, slot: ItemSlot, item: Item, count?: number): this {
    this.$set(litPart("item"), litPart("replace"), litPart("entity"), argPart(targets), argPart(slot), litPart("with"), argPart(item));
    if (count !== undefined) this.$append(argPart(count));
    return this;
  }
}

export class ItemHandler extends TreeCommandHandler<ItemNode> {
  readonly type: ItemNode["type"] = "item";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `item` - `ctx.item()...` */
    item(): ItemBuilder;
  }
}

FunctionContext.prototype.item = function (this: FunctionContext) {
  const node = new ItemNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("item")];
  node.parts = parts;
  return new ItemBuilder(node);
};
