// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `jfr` */
export class JfrNode extends CommandNodeBase {
  readonly type = "jfr";
}

export class JfrBuilder extends CommandBuilder<JfrNode> {
  start(): this {
    this.$set(litPart("jfr"), litPart("start"));
    return this;
  }

  stop(): this {
    this.$set(litPart("jfr"), litPart("stop"));
    return this;
  }
}

export class JfrHandler extends TreeCommandHandler<JfrNode> {
  readonly type: JfrNode["type"] = "jfr";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `jfr` - `ctx.jfr()...` */
    jfr(): JfrBuilder;
  }
}

FunctionContext.prototype.jfr = function (this: FunctionContext) {
  const node = new JfrNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("jfr")];
  node.parts = parts;
  return new JfrBuilder(node);
};
