// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `kick` */
export class KickNode extends CommandNodeBase {
  readonly type = "kick";
}

export class KickBuilder extends CommandBuilder<KickNode> {

}

export class KickHandler extends TreeCommandHandler<KickNode> {
  readonly type: KickNode["type"] = "kick";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `kick` - `ctx.kick()...` */
    kick(targets: Selector, reason?: Message): KickBuilder;
  }
}

FunctionContext.prototype.kick = function (this: FunctionContext, targets: Selector, reason?: Message) {
  const node = new KickNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("kick"), argPart(targets)];
  if (reason !== undefined) parts.push(argPart(reason));
  node.parts = parts;
  return new KickBuilder(node);
};
