// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `kill` */
export class KillBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `kill` - `ctx.kill()...` */
    kill(targets?: Selector): KillBuilder;
  }
}

FunctionContext.prototype.kill = function (this: FunctionContext, targets?: Selector) {
  const node = new TreeCommandNode("kill");
  this.emit(node);
  const parts: CommandPart[] = [litPart("kill")];
  if (targets !== undefined) parts.push(argPart(targets));
  node.parts = parts;
  return new KillBuilder(node);
};
