// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `kill` */
export class KillNode extends CommandNodeBase {
  readonly type = "kill";
}

export class KillBuilder extends CommandBuilder<KillNode> {

}

export class KillHandler extends TreeCommandHandler<KillNode> {
  readonly type: KillNode["type"] = "kill";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `kill` - `ctx.kill()...` */
    kill(targets?: Selector): KillBuilder;
  }
}

FunctionContext.prototype.kill = function (this: FunctionContext, targets?: Selector) {
  const node = new KillNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("kill")];
  if (targets !== undefined) parts.push(argPart(targets));
  node.parts = parts;
  return new KillBuilder(node);
};
