// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `list` */
export class ListNode extends CommandNodeBase {
  readonly type = "list";
}

export class ListBuilder extends CommandBuilder<ListNode> {
  uuids(): this {
    this.$set(litPart("list"), litPart("uuids"));
    return this;
  }
}

export class ListHandler extends TreeCommandHandler<ListNode> {
  readonly type: ListNode["type"] = "list";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `list` - `ctx.list()...` */
    list(): ListBuilder;
  }
}

FunctionContext.prototype.list = function (this: FunctionContext) {
  const node = new ListNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("list")];
  node.parts = parts;
  return new ListBuilder(node);
};
