// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Biome, PointOfInterestType, Structure } from "../values";

/** `locate` */
export class LocateNode extends CommandNodeBase {
  readonly type = "locate";
}

export class LocateBuilder extends CommandBuilder<LocateNode> {
  biome(biome: Biome): this {
    this.$set(litPart("locate"), litPart("biome"), argPart(biome));
    return this;
  }

  poi(poi: PointOfInterestType): this {
    this.$set(litPart("locate"), litPart("poi"), argPart(poi));
    return this;
  }

  structure(structure: Structure): this {
    this.$set(litPart("locate"), litPart("structure"), argPart(structure));
    return this;
  }
}

export class LocateHandler extends TreeCommandHandler<LocateNode> {
  readonly type: LocateNode["type"] = "locate";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `locate` - `ctx.locate()...` */
    locate(): LocateBuilder;
  }
}

FunctionContext.prototype.locate = function (this: FunctionContext) {
  const node = new LocateNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("locate")];
  node.parts = parts;
  return new LocateBuilder(node);
};
