// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Biome, PointOfInterestType, Structure } from "../values";

/** `locate` */
export class LocateBuilder extends CommandBuilder<TreeCommandNode> {
  biome(biome: Biome): this {
    this.$set(litPart("locate"), litPart("biome"), argPart(biome));
    return this;
  }

  poi(poi: PointOfInterestType): this {
    this.$set(litPart("locate"), litPart("poi"), argPart(poi));
    return this;
  }

  structure(structure: Structure): this {
    this.$set(litPart("locate"), litPart("structure"), argPart(structure));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `locate` - `ctx.locate()...` */
    locate(): LocateBuilder;
  }
}

FunctionContext.prototype.locate = function (this: FunctionContext) {
  const node = new TreeCommandNode("locate");
  this.emit(node);
  const parts: CommandPart[] = [litPart("locate")];
  node.parts = parts;
  return new LocateBuilder(node);
};
