// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";

/** `me` */
export class MeNode extends CommandNodeBase {
  readonly type = "me";
}

export class MeBuilder extends CommandBuilder<MeNode> {

}

export class MeHandler extends TreeCommandHandler<MeNode> {
  readonly type: MeNode["type"] = "me";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `me` - `ctx.me()...` */
    me(action: Message): MeBuilder;
  }
}

FunctionContext.prototype.me = function (this: FunctionContext, action: Message) {
  const node = new MeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("me"), argPart(action)];
  node.parts = parts;
  return new MeBuilder(node);
};
