// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `msg` */
export class MsgNode extends CommandNodeBase {
  readonly type = "msg";
}

export class MsgBuilder extends CommandBuilder<MsgNode> {

}

export class MsgHandler extends TreeCommandHandler<MsgNode> {
  readonly type: MsgNode["type"] = "msg";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `msg` - `ctx.msg()...` */
    msg(targets: Selector, message: Message): MsgBuilder;
  }
}

FunctionContext.prototype.msg = function (this: FunctionContext, targets: Selector, message: Message) {
  const node = new MsgNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("msg"), argPart(targets), argPart(message)];
  node.parts = parts;
  return new MsgBuilder(node);
};
