// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `op` */
export class OpNode extends CommandNodeBase {
  readonly type = "op";
}

export class OpBuilder extends CommandBuilder<OpNode> {

}

export class OpHandler extends TreeCommandHandler<OpNode> {
  readonly type: OpNode["type"] = "op";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `op` - `ctx.op()...` */
    op(targets: Selector): OpBuilder;
  }
}

FunctionContext.prototype.op = function (this: FunctionContext, targets: Selector) {
  const node = new OpNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("op"), argPart(targets)];
  node.parts = parts;
  return new OpBuilder(node);
};
