// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `pardon` */
export class PardonNode extends CommandNodeBase {
  readonly type = "pardon";
}

export class PardonBuilder extends CommandBuilder<PardonNode> {

}

export class PardonHandler extends TreeCommandHandler<PardonNode> {
  readonly type: PardonNode["type"] = "pardon";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `pardon` - `ctx.pardon()...` */
    pardon(targets: Selector): PardonBuilder;
  }
}

FunctionContext.prototype.pardon = function (this: FunctionContext, targets: Selector) {
  const node = new PardonNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("pardon"), argPart(targets)];
  node.parts = parts;
  return new PardonBuilder(node);
};
