// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `pardon-ip` */
export class PardonIpNode extends CommandNodeBase {
  readonly type = "pardon-ip";
}

export class PardonIpBuilder extends CommandBuilder<PardonIpNode> {

}

export class PardonIpHandler extends TreeCommandHandler<PardonIpNode> {
  readonly type: PardonIpNode["type"] = "pardon-ip";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `pardon-ip` - `ctx.pardonIp()...` */
    pardonIp(target: string): PardonIpBuilder;
  }
}

FunctionContext.prototype.pardonIp = function (this: FunctionContext, target: string) {
  const node = new PardonIpNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("pardon-ip"), argPart(target)];
  node.parts = parts;
  return new PardonIpBuilder(node);
};
