// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Particle, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `particle` */
export class ParticleNode extends CommandNodeBase {
  readonly type = "particle";
}

export class ParticleBuilder extends CommandBuilder<ParticleNode> {
  force(name: Particle, pos: Pos, delta: Pos, speed: number, count: number, viewers?: Selector): this {
    this.$set(litPart("particle"), argPart(name), argPart(pos), argPart(delta), argPart(speed), argPart(count), litPart("force"));
    if (viewers !== undefined) this.$append(argPart(viewers));
    return this;
  }

  normal(name: Particle, pos: Pos, delta: Pos, speed: number, count: number, viewers?: Selector): this {
    this.$set(litPart("particle"), argPart(name), argPart(pos), argPart(delta), argPart(speed), argPart(count), litPart("normal"));
    if (viewers !== undefined) this.$append(argPart(viewers));
    return this;
  }
}

export class ParticleHandler extends TreeCommandHandler<ParticleNode> {
  readonly type: ParticleNode["type"] = "particle";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `particle` - `ctx.particle()...` */
    particle(name?: Particle, pos?: Pos, delta?: Pos, speed?: number, count?: number): ParticleBuilder;
  }
}

FunctionContext.prototype.particle = function (this: FunctionContext, name?: Particle, pos?: Pos, delta?: Pos, speed?: number, count?: number) {
  const node = new ParticleNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("particle")];
  if (name !== undefined) parts.push(argPart(name));
  if (pos !== undefined) parts.push(argPart(pos));
  if (delta !== undefined) parts.push(argPart(delta));
  if (speed !== undefined) parts.push(argPart(speed));
  if (count !== undefined) parts.push(argPart(count));
  node.parts = parts;
  return new ParticleBuilder(node);
};
