// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `perf` */
export class PerfNode extends CommandNodeBase {
  readonly type = "perf";
}

export class PerfBuilder extends CommandBuilder<PerfNode> {
  start(): this {
    this.$set(litPart("perf"), litPart("start"));
    return this;
  }

  stop(): this {
    this.$set(litPart("perf"), litPart("stop"));
    return this;
  }
}

export class PerfHandler extends TreeCommandHandler<PerfNode> {
  readonly type: PerfNode["type"] = "perf";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `perf` - `ctx.perf()...` */
    perf(): PerfBuilder;
  }
}

FunctionContext.prototype.perf = function (this: FunctionContext) {
  const node = new PerfNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("perf")];
  node.parts = parts;
  return new PerfBuilder(node);
};
