// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { ConfiguredFeature, Id, Pos, Structure, TemplateMirror, TemplatePool, TemplateRotation } from "../values";

/** `place` */
export class PlaceNode extends CommandNodeBase {
  readonly type = "place";
}

export class PlaceBuilder extends CommandBuilder<PlaceNode> {
  feature(feature: ConfiguredFeature, pos?: Pos): this {
    this.$set(litPart("place"), litPart("feature"), argPart(feature));
    if (pos !== undefined) this.$append(argPart(pos));
    return this;
  }

  jigsaw(pool: TemplatePool, target: Id, max_depth: number, position?: Pos): this {
    this.$set(litPart("place"), litPart("jigsaw"), argPart(pool), argPart(target), argPart(max_depth));
    if (position !== undefined) this.$append(argPart(position));
    return this;
  }

  structure(structure: Structure, pos?: Pos): this {
    this.$set(litPart("place"), litPart("structure"), argPart(structure));
    if (pos !== undefined) this.$append(argPart(pos));
    return this;
  }

  template(template: Id, pos?: Pos, rotation?: TemplateRotation, mirror?: TemplateMirror, integrity?: number, seed?: number): this {
    this.$set(litPart("place"), litPart("template"), argPart(template));
    if (pos !== undefined) this.$append(argPart(pos));
    if (rotation !== undefined) this.$append(argPart(rotation));
    if (mirror !== undefined) this.$append(argPart(mirror));
    if (integrity !== undefined) this.$append(argPart(integrity));
    if (seed !== undefined) this.$append(argPart(seed));
    return this;
  }

  templateStrict(template: Id, pos: Pos, rotation: TemplateRotation, mirror: TemplateMirror, integrity: number, seed: number): this {
    this.$set(litPart("place"), litPart("template"), argPart(template), argPart(pos), argPart(rotation), argPart(mirror), argPart(integrity), argPart(seed), litPart("strict"));
    return this;
  }
}

export class PlaceHandler extends TreeCommandHandler<PlaceNode> {
  readonly type: PlaceNode["type"] = "place";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `place` - `ctx.place()...` */
    place(): PlaceBuilder;
  }
}

FunctionContext.prototype.place = function (this: FunctionContext) {
  const node = new PlaceNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("place")];
  node.parts = parts;
  return new PlaceBuilder(node);
};
