// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Id, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `playsound` */
export class PlaysoundNode extends CommandNodeBase {
  readonly type = "playsound";
}

export class PlaysoundBuilder extends CommandBuilder<PlaysoundNode> {
  ambient(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("ambient"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  block(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("block"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  hostile(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("hostile"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  master(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("master"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  music(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("music"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  neutral(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("neutral"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  player(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("player"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  record(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("record"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  ui(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("ui"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  voice(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("voice"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  weather(sound: Id, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("weather"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }
}

export class PlaysoundHandler extends TreeCommandHandler<PlaysoundNode> {
  readonly type: PlaysoundNode["type"] = "playsound";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `playsound` - `ctx.playsound()...` */
    playsound(sound?: Id): PlaysoundBuilder;
  }
}

FunctionContext.prototype.playsound = function (this: FunctionContext, sound?: Id) {
  const node = new PlaysoundNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("playsound")];
  if (sound !== undefined) parts.push(argPart(sound));
  node.parts = parts;
  return new PlaysoundBuilder(node);
};
