// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos, SoundEvent } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `playsound` */
export class PlaysoundBuilder extends CommandBuilder<TreeCommandNode> {
  ambient(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("ambient"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  block(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("block"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  hostile(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("hostile"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  master(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("master"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  music(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("music"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  neutral(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("neutral"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  player(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("player"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  record(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("record"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  ui(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("ui"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  voice(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("voice"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }

  weather(sound: SoundEvent, targets?: Selector, pos?: Pos, volume?: number, pitch?: number, minVolume?: number): this {
    this.$set(litPart("playsound"), argPart(sound), litPart("weather"));
    if (targets !== undefined) this.$append(argPart(targets));
    if (pos !== undefined) this.$append(argPart(pos));
    if (volume !== undefined) this.$append(argPart(volume));
    if (pitch !== undefined) this.$append(argPart(pitch));
    if (minVolume !== undefined) this.$append(argPart(minVolume));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `playsound` - `ctx.playsound()...` */
    playsound(sound?: SoundEvent): PlaysoundBuilder;
  }
}

FunctionContext.prototype.playsound = function (this: FunctionContext, sound?: SoundEvent) {
  const node = new TreeCommandNode("playsound");
  this.emit(node);
  const parts: CommandPart[] = [litPart("playsound")];
  if (sound !== undefined) parts.push(argPart(sound));
  node.parts = parts;
  return new PlaysoundBuilder(node);
};
