// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { Effect } from "../ir/line-info";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Id } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `posteffect` */
export class PosteffectBuilder extends CommandBuilder<TreeCommandNode> {
  add(targets: Selector, posteffect: Id): this {
    this.$set(litPart("posteffect"), litPart("add"), argPart(targets), argPart(posteffect));
    return this;
  }

  clear(targets: Selector): this {
    this.$set(litPart("posteffect"), litPart("clear"), argPart(targets));
    return this;
  }

  list(target: Selector): this {
    this.$set(litPart("posteffect"), litPart("list"), argPart(target));
    return this;
  }

  remove(targets: Selector, posteffect: Id): this {
    this.$set(litPart("posteffect"), litPart("remove"), argPart(targets), argPart(posteffect));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `posteffect` - `ctx.posteffect()...` */
    posteffect(): PosteffectBuilder;
  }
}

FunctionContext.prototype.posteffect = function (this: FunctionContext) {
  const node = new TreeCommandNode("posteffect", { effect: Effect.NONE });
  this.emit(node);
  const parts: CommandPart[] = [litPart("posteffect")];
  node.parts = parts;
  return new PosteffectBuilder(node);
};
