// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Gamemode } from "../values";

/** `publish` */
export class PublishNode extends CommandNodeBase {
  readonly type = "publish";
}

export class PublishBuilder extends CommandBuilder<PublishNode> {

}

export class PublishHandler extends TreeCommandHandler<PublishNode> {
  readonly type: PublishNode["type"] = "publish";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `publish` - `ctx.publish()...` */
    publish(allowCommands?: boolean, gamemode?: Gamemode, port?: number): PublishBuilder;
  }
}

FunctionContext.prototype.publish = function (this: FunctionContext, allowCommands?: boolean, gamemode?: Gamemode, port?: number) {
  const node = new PublishNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("publish")];
  if (allowCommands !== undefined) parts.push(argPart(allowCommands));
  if (gamemode !== undefined) parts.push(argPart(gamemode));
  if (port !== undefined) parts.push(argPart(port));
  node.parts = parts;
  return new PublishBuilder(node);
};
