// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `recipe` */
export class RecipeNode extends CommandNodeBase {
  readonly type = "recipe";
}

export class RecipeBuilder extends CommandBuilder<RecipeNode> {
  give(targets: Selector): this {
    this.$set(litPart("recipe"), litPart("give"), argPart(targets), litPart("*"));
    return this;
  }

  take(targets: Selector): this {
    this.$set(litPart("recipe"), litPart("take"), argPart(targets), litPart("*"));
    return this;
  }
}

export class RecipeHandler extends TreeCommandHandler<RecipeNode> {
  readonly type: RecipeNode["type"] = "recipe";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `recipe` - `ctx.recipe()...` */
    recipe(): RecipeBuilder;
  }
}

FunctionContext.prototype.recipe = function (this: FunctionContext) {
  const node = new RecipeNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("recipe")];
  node.parts = parts;
  return new RecipeBuilder(node);
};
