// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `recipe` */
export class RecipeBuilder extends CommandBuilder<TreeCommandNode> {
  give(targets: Selector): this {
    this.$set(litPart("recipe"), litPart("give"), argPart(targets), litPart("*"));
    return this;
  }

  take(targets: Selector): this {
    this.$set(litPart("recipe"), litPart("take"), argPart(targets), litPart("*"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `recipe` - `ctx.recipe()...` */
    recipe(): RecipeBuilder;
  }
}

FunctionContext.prototype.recipe = function (this: FunctionContext) {
  const node = new TreeCommandNode("recipe");
  this.emit(node);
  const parts: CommandPart[] = [litPart("recipe")];
  node.parts = parts;
  return new RecipeBuilder(node);
};
