// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `reload` */
export class ReloadNode extends CommandNodeBase {
  readonly type = "reload";
}

export class ReloadBuilder extends CommandBuilder<ReloadNode> {

}

export class ReloadHandler extends TreeCommandHandler<ReloadNode> {
  readonly type: ReloadNode["type"] = "reload";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `reload` - `ctx.reload()...` */
    reload(): ReloadBuilder;
  }
}

FunctionContext.prototype.reload = function (this: FunctionContext) {
  const node = new ReloadNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("reload")];
  node.parts = parts;
  return new ReloadBuilder(node);
};
