// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `reload` */
export class ReloadBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `reload` - `ctx.reload()...` */
    reload(): ReloadBuilder;
  }
}

FunctionContext.prototype.reload = function (this: FunctionContext) {
  const node = new TreeCommandNode("reload");
  this.emit(node);
  const parts: CommandPart[] = [litPart("reload")];
  node.parts = parts;
  return new ReloadBuilder(node);
};
