// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `return` */
export class ReturnBuilder extends CommandBuilder<TreeCommandNode> {
  fail(): this {
    this.$set(litPart("return"), litPart("fail"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `return` - `ctx.return_()...` */
    return_(value?: number): ReturnBuilder;
  }
}

FunctionContext.prototype.return_ = function (this: FunctionContext, value?: number) {
  const node = new TreeCommandNode("return");
  this.emit(node);
  const parts: CommandPart[] = [litPart("return")];
  if (value !== undefined) parts.push(argPart(value));
  node.parts = parts;
  return new ReturnBuilder(node);
};
