// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `return` */
export class ReturnNode extends CommandNodeBase {
  readonly type = "return";
}

export class ReturnBuilder extends CommandBuilder<ReturnNode> {
  fail(): this {
    this.$set(litPart("return"), litPart("fail"));
    return this;
  }
}

export class ReturnHandler extends TreeCommandHandler<ReturnNode> {
  readonly type: ReturnNode["type"] = "return";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `return` - `ctx.return_()...` */
    return_(value?: number): ReturnBuilder;
  }
}

FunctionContext.prototype.return_ = function (this: FunctionContext, value?: number) {
  const node = new ReturnNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("return")];
  if (value !== undefined) parts.push(argPart(value));
  node.parts = parts;
  return new ReturnBuilder(node);
};
