// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `ride` */
export class RideBuilder extends CommandBuilder<TreeCommandNode> {
  dismount(target: Selector): this {
    this.$set(litPart("ride"), argPart(target), litPart("dismount"));
    return this;
  }

  mount(target: Selector, vehicle: Selector): this {
    this.$set(litPart("ride"), argPart(target), litPart("mount"), argPart(vehicle));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `ride` - `ctx.ride()...` */
    ride(): RideBuilder;
  }
}

FunctionContext.prototype.ride = function (this: FunctionContext) {
  const node = new TreeCommandNode("ride");
  this.emit(node);
  const parts: CommandPart[] = [litPart("ride")];
  node.parts = parts;
  return new RideBuilder(node);
};
