// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `ride` */
export class RideNode extends CommandNodeBase {
  readonly type = "ride";
}

export class RideBuilder extends CommandBuilder<RideNode> {
  dismount(target: Selector): this {
    this.$set(litPart("ride"), argPart(target), litPart("dismount"));
    return this;
  }

  mount(target: Selector, vehicle: Selector): this {
    this.$set(litPart("ride"), argPart(target), litPart("mount"), argPart(vehicle));
    return this;
  }
}

export class RideHandler extends TreeCommandHandler<RideNode> {
  readonly type: RideNode["type"] = "ride";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `ride` - `ctx.ride()...` */
    ride(): RideBuilder;
  }
}

FunctionContext.prototype.ride = function (this: FunctionContext) {
  const node = new RideNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("ride")];
  node.parts = parts;
  return new RideBuilder(node);
};
