// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { EntityAnchor, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `rotate` */
export class RotateNode extends CommandNodeBase {
  readonly type = "rotate";
}

export class RotateBuilder extends CommandBuilder<RotateNode> {
  facing(target: Selector, facingLocation: Pos): this {
    this.$set(litPart("rotate"), argPart(target), litPart("facing"), argPart(facingLocation));
    return this;
  }

  facingEntity(target: Selector, facingEntity: Selector, facingAnchor?: EntityAnchor): this {
    this.$set(litPart("rotate"), argPart(target), litPart("facing"), litPart("entity"), argPart(facingEntity));
    if (facingAnchor !== undefined) this.$append(argPart(facingAnchor));
    return this;
  }
}

export class RotateHandler extends TreeCommandHandler<RotateNode> {
  readonly type: RotateNode["type"] = "rotate";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `rotate` - `ctx.rotate()...` */
    rotate(target?: Selector, rotation?: Pos): RotateBuilder;
  }
}

FunctionContext.prototype.rotate = function (this: FunctionContext, target?: Selector, rotation?: Pos) {
  const node = new RotateNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("rotate")];
  if (target !== undefined) parts.push(argPart(target));
  if (rotation !== undefined) parts.push(argPart(rotation));
  node.parts = parts;
  return new RotateBuilder(node);
};
