// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `save-all` */
export class SaveAllNode extends CommandNodeBase {
  readonly type = "save-all";
}

export class SaveAllBuilder extends CommandBuilder<SaveAllNode> {
  flush(): this {
    this.$set(litPart("save-all"), litPart("flush"));
    return this;
  }
}

export class SaveAllHandler extends TreeCommandHandler<SaveAllNode> {
  readonly type: SaveAllNode["type"] = "save-all";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `save-all` - `ctx.saveAll()...` */
    saveAll(): SaveAllBuilder;
  }
}

FunctionContext.prototype.saveAll = function (this: FunctionContext) {
  const node = new SaveAllNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("save-all")];
  node.parts = parts;
  return new SaveAllBuilder(node);
};
