// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `save-on` */
export class SaveOnNode extends CommandNodeBase {
  readonly type = "save-on";
}

export class SaveOnBuilder extends CommandBuilder<SaveOnNode> {

}

export class SaveOnHandler extends TreeCommandHandler<SaveOnNode> {
  readonly type: SaveOnNode["type"] = "save-on";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `save-on` - `ctx.saveOn()...` */
    saveOn(): SaveOnBuilder;
  }
}

FunctionContext.prototype.saveOn = function (this: FunctionContext) {
  const node = new SaveOnNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("save-on")];
  node.parts = parts;
  return new SaveOnBuilder(node);
};
