// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `save-off` */
export class SaveOffNode extends CommandNodeBase {
  readonly type = "save-off";
}

export class SaveOffBuilder extends CommandBuilder<SaveOffNode> {

}

export class SaveOffHandler extends TreeCommandHandler<SaveOffNode> {
  readonly type: SaveOffNode["type"] = "save-off";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `save-off` - `ctx.saveOff()...` */
    saveOff(): SaveOffBuilder;
  }
}

FunctionContext.prototype.saveOff = function (this: FunctionContext) {
  const node = new SaveOffNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("save-off")];
  node.parts = parts;
  return new SaveOffBuilder(node);
};
