// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { FunctionId, Time } from "../values";

/** `schedule` */
export class ScheduleNode extends CommandNodeBase {
  readonly type = "schedule";
}

export class ScheduleBuilder extends CommandBuilder<ScheduleNode> {
  clear(function_: string): this {
    this.$set(litPart("schedule"), litPart("clear"), argPart(function_));
    return this;
  }

  function_(function_: FunctionId, time: Time): this {
    this.$set(litPart("schedule"), litPart("function"), argPart(function_), argPart(time));
    return this;
  }

  functionAppend(function_: FunctionId, time: Time): this {
    this.$set(litPart("schedule"), litPart("function"), argPart(function_), argPart(time), litPart("append"));
    return this;
  }

  functionReplace(function_: FunctionId, time: Time): this {
    this.$set(litPart("schedule"), litPart("function"), argPart(function_), argPart(time), litPart("replace"));
    return this;
  }
}

export class ScheduleHandler extends TreeCommandHandler<ScheduleNode> {
  readonly type: ScheduleNode["type"] = "schedule";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `schedule` - `ctx.schedule()...` */
    schedule(): ScheduleBuilder;
  }
}

FunctionContext.prototype.schedule = function (this: FunctionContext) {
  const node = new ScheduleNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("schedule")];
  node.parts = parts;
  return new ScheduleBuilder(node);
};
