// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `seed` */
export class SeedNode extends CommandNodeBase {
  readonly type = "seed";
}

export class SeedBuilder extends CommandBuilder<SeedNode> {

}

export class SeedHandler extends TreeCommandHandler<SeedNode> {
  readonly type: SeedNode["type"] = "seed";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `seed` - `ctx.seed()...` */
    seed(): SeedBuilder;
  }
}

FunctionContext.prototype.seed = function (this: FunctionContext) {
  const node = new SeedNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("seed")];
  node.parts = parts;
  return new SeedBuilder(node);
};
