// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";

/** `setidletimeout` */
export class SetidletimeoutNode extends CommandNodeBase {
  readonly type = "setidletimeout";
}

export class SetidletimeoutBuilder extends CommandBuilder<SetidletimeoutNode> {

}

export class SetidletimeoutHandler extends TreeCommandHandler<SetidletimeoutNode> {
  readonly type: SetidletimeoutNode["type"] = "setidletimeout";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `setidletimeout` - `ctx.setidletimeout()...` */
    setidletimeout(minutes: number): SetidletimeoutBuilder;
  }
}

FunctionContext.prototype.setidletimeout = function (this: FunctionContext, minutes: number) {
  const node = new SetidletimeoutNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("setidletimeout"), argPart(minutes)];
  node.parts = parts;
  return new SetidletimeoutBuilder(node);
};
