// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos } from "../values";

/** `setworldspawn` */
export class SetworldspawnBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `setworldspawn` - `ctx.setworldspawn()...` */
    setworldspawn(pos?: Pos, rotation?: Pos): SetworldspawnBuilder;
  }
}

FunctionContext.prototype.setworldspawn = function (this: FunctionContext, pos?: Pos, rotation?: Pos) {
  const node = new TreeCommandNode("setworldspawn");
  this.emit(node);
  const parts: CommandPart[] = [litPart("setworldspawn")];
  if (pos !== undefined) parts.push(argPart(pos));
  if (rotation !== undefined) parts.push(argPart(rotation));
  node.parts = parts;
  return new SetworldspawnBuilder(node);
};
