// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `spawnpoint` */
export class SpawnpointNode extends CommandNodeBase {
  readonly type = "spawnpoint";
}

export class SpawnpointBuilder extends CommandBuilder<SpawnpointNode> {

}

export class SpawnpointHandler extends TreeCommandHandler<SpawnpointNode> {
  readonly type: SpawnpointNode["type"] = "spawnpoint";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `spawnpoint` - `ctx.spawnpoint()...` */
    spawnpoint(targets?: Selector, pos?: Pos, rotation?: Pos): SpawnpointBuilder;
  }
}

FunctionContext.prototype.spawnpoint = function (this: FunctionContext, targets?: Selector, pos?: Pos, rotation?: Pos) {
  const node = new SpawnpointNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("spawnpoint")];
  if (targets !== undefined) parts.push(argPart(targets));
  if (pos !== undefined) parts.push(argPart(pos));
  if (rotation !== undefined) parts.push(argPart(rotation));
  node.parts = parts;
  return new SpawnpointBuilder(node);
};
