// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `spawnpoint` */
export class SpawnpointBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `spawnpoint` - `ctx.spawnpoint()...` */
    spawnpoint(targets?: Selector, pos?: Pos, rotation?: Pos): SpawnpointBuilder;
  }
}

FunctionContext.prototype.spawnpoint = function (this: FunctionContext, targets?: Selector, pos?: Pos, rotation?: Pos) {
  const node = new TreeCommandNode("spawnpoint");
  this.emit(node);
  const parts: CommandPart[] = [litPart("spawnpoint")];
  if (targets !== undefined) parts.push(argPart(targets));
  if (pos !== undefined) parts.push(argPart(pos));
  if (rotation !== undefined) parts.push(argPart(rotation));
  node.parts = parts;
  return new SpawnpointBuilder(node);
};
