// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `spectate` */
export class SpectateNode extends CommandNodeBase {
  readonly type = "spectate";
}

export class SpectateBuilder extends CommandBuilder<SpectateNode> {

}

export class SpectateHandler extends TreeCommandHandler<SpectateNode> {
  readonly type: SpectateNode["type"] = "spectate";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `spectate` - `ctx.spectate()...` */
    spectate(target?: Selector, player?: Selector): SpectateBuilder;
  }
}

FunctionContext.prototype.spectate = function (this: FunctionContext, target?: Selector, player?: Selector) {
  const node = new SpectateNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("spectate")];
  if (target !== undefined) parts.push(argPart(target));
  if (player !== undefined) parts.push(argPart(player));
  node.parts = parts;
  return new SpectateBuilder(node);
};
