// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `spreadplayers` */
export class SpreadplayersBuilder extends CommandBuilder<TreeCommandNode> {
  under(center: Pos, spreadDistance: number, maxRange: number, maxHeight: number, respectTeams: boolean, targets: Selector): this {
    this.$set(litPart("spreadplayers"), argPart(center), argPart(spreadDistance), argPart(maxRange), litPart("under"), argPart(maxHeight), argPart(respectTeams), argPart(targets));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `spreadplayers` - `ctx.spreadplayers()...` */
    spreadplayers(center?: Pos, spreadDistance?: number, maxRange?: number, respectTeams?: boolean, targets?: Selector): SpreadplayersBuilder;
  }
}

FunctionContext.prototype.spreadplayers = function (this: FunctionContext, center?: Pos, spreadDistance?: number, maxRange?: number, respectTeams?: boolean, targets?: Selector) {
  const node = new TreeCommandNode("spreadplayers");
  this.emit(node);
  const parts: CommandPart[] = [litPart("spreadplayers")];
  if (center !== undefined) parts.push(argPart(center));
  if (spreadDistance !== undefined) parts.push(argPart(spreadDistance));
  if (maxRange !== undefined) parts.push(argPart(maxRange));
  if (respectTeams !== undefined) parts.push(argPart(respectTeams));
  if (targets !== undefined) parts.push(argPart(targets));
  node.parts = parts;
  return new SpreadplayersBuilder(node);
};
