// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `stop` */
export class StopNode extends CommandNodeBase {
  readonly type = "stop";
}

export class StopBuilder extends CommandBuilder<StopNode> {

}

export class StopHandler extends TreeCommandHandler<StopNode> {
  readonly type: StopNode["type"] = "stop";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `stop` - `ctx.stop()...` */
    stop(): StopBuilder;
  }
}

FunctionContext.prototype.stop = function (this: FunctionContext) {
  const node = new StopNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("stop")];
  node.parts = parts;
  return new StopBuilder(node);
};
