// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Id } from "../values";

/** `stopwatch` */
export class StopwatchNode extends CommandNodeBase {
  readonly type = "stopwatch";
}

export class StopwatchBuilder extends CommandBuilder<StopwatchNode> {
  create(id: Id): this {
    this.$set(litPart("stopwatch"), litPart("create"), argPart(id));
    return this;
  }

  query(id: Id, scale?: number): this {
    this.$set(litPart("stopwatch"), litPart("query"), argPart(id));
    if (scale !== undefined) this.$append(argPart(scale));
    return this;
  }

  remove(id: Id): this {
    this.$set(litPart("stopwatch"), litPart("remove"), argPart(id));
    return this;
  }

  restart(id: Id): this {
    this.$set(litPart("stopwatch"), litPart("restart"), argPart(id));
    return this;
  }
}

export class StopwatchHandler extends TreeCommandHandler<StopwatchNode> {
  readonly type: StopwatchNode["type"] = "stopwatch";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `stopwatch` - `ctx.stopwatch()...` */
    stopwatch(): StopwatchBuilder;
  }
}

FunctionContext.prototype.stopwatch = function (this: FunctionContext) {
  const node = new StopwatchNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("stopwatch")];
  node.parts = parts;
  return new StopwatchBuilder(node);
};
