// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { EntityType, Nbt, Pos } from "../values";

/** `summon` */
export class SummonBuilder extends CommandBuilder<TreeCommandNode> {

}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `summon` - `ctx.summon()...` */
    summon(entity: EntityType, pos?: Pos, nbt?: Nbt): SummonBuilder;
  }
}

FunctionContext.prototype.summon = function (this: FunctionContext, entity: EntityType, pos?: Pos, nbt?: Nbt) {
  const node = new TreeCommandNode("summon");
  this.emit(node);
  const parts: CommandPart[] = [litPart("summon"), argPart(entity)];
  if (pos !== undefined) parts.push(argPart(pos));
  if (nbt !== undefined) parts.push(argPart(nbt));
  node.parts = parts;
  return new SummonBuilder(node);
};
