// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `swing` */
export class SwingBuilder extends CommandBuilder<TreeCommandNode> {
  mainhand(targets: Selector): this {
    this.$set(litPart("swing"), argPart(targets), litPart("mainhand"));
    return this;
  }

  offhand(targets: Selector): this {
    this.$set(litPart("swing"), argPart(targets), litPart("offhand"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `swing` - `ctx.swing()...` */
    swing(targets?: Selector): SwingBuilder;
  }
}

FunctionContext.prototype.swing = function (this: FunctionContext, targets?: Selector) {
  const node = new TreeCommandNode("swing");
  this.emit(node);
  const parts: CommandPart[] = [litPart("swing")];
  if (targets !== undefined) parts.push(argPart(targets));
  node.parts = parts;
  return new SwingBuilder(node);
};
