// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `tag` */
export class TagNode extends CommandNodeBase {
  readonly type = "tag";
}

export class TagBuilder extends CommandBuilder<TagNode> {
  add(targets: Selector, name: string): this {
    this.$set(litPart("tag"), argPart(targets), litPart("add"), argPart(name));
    return this;
  }

  list(targets: Selector): this {
    this.$set(litPart("tag"), argPart(targets), litPart("list"));
    return this;
  }

  remove(targets: Selector, name: string): this {
    this.$set(litPart("tag"), argPart(targets), litPart("remove"), argPart(name));
    return this;
  }
}

export class TagHandler extends TreeCommandHandler<TagNode> {
  readonly type: TagNode["type"] = "tag";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `tag` - `ctx.tag()...` */
    tag(): TagBuilder;
  }
}

FunctionContext.prototype.tag = function (this: FunctionContext) {
  const node = new TagNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("tag")];
  node.parts = parts;
  return new TagBuilder(node);
};
