// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Component, Team, TeamColor } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `team` */
export class TeamBuilder extends CommandBuilder<TreeCommandNode> {
  add(team: string, displayName?: Component): this {
    this.$set(litPart("team"), litPart("add"), argPart(team));
    if (displayName !== undefined) this.$append(argPart(displayName));
    return this;
  }

  empty(team: Team): this {
    this.$set(litPart("team"), litPart("empty"), argPart(team));
    return this;
  }

  join(team: Team, members?: Selector): this {
    this.$set(litPart("team"), litPart("join"), argPart(team));
    if (members !== undefined) this.$append(argPart(members));
    return this;
  }

  leave(members: Selector): this {
    this.$set(litPart("team"), litPart("leave"), argPart(members));
    return this;
  }

  list(team?: Team): this {
    this.$set(litPart("team"), litPart("list"));
    if (team !== undefined) this.$append(argPart(team));
    return this;
  }

  modifyCollisionRuleAlways(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("collisionRule"), litPart("always"));
    return this;
  }

  modifyCollisionRuleNever(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("collisionRule"), litPart("never"));
    return this;
  }

  modifyCollisionRulePushOtherTeams(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("collisionRule"), litPart("pushOtherTeams"));
    return this;
  }

  modifyCollisionRulePushOwnTeam(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("collisionRule"), litPart("pushOwnTeam"));
    return this;
  }

  modifyColor(team: Team, value: TeamColor): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("color"), argPart(value));
    return this;
  }

  modifyColorReset(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("color"), litPart("reset"));
    return this;
  }

  modifyDeathMessageVisibilityAlways(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("deathMessageVisibility"), litPart("always"));
    return this;
  }

  modifyDeathMessageVisibilityHideForOtherTeams(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("deathMessageVisibility"), litPart("hideForOtherTeams"));
    return this;
  }

  modifyDeathMessageVisibilityHideForOwnTeam(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("deathMessageVisibility"), litPart("hideForOwnTeam"));
    return this;
  }

  modifyDeathMessageVisibilityNever(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("deathMessageVisibility"), litPart("never"));
    return this;
  }

  modifyDisplayName(team: Team, displayName: Component): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("displayName"), argPart(displayName));
    return this;
  }

  modifyFriendlyFire(team: Team, allowed: boolean): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("friendlyFire"), argPart(allowed));
    return this;
  }

  modifyNametagVisibilityAlways(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("nametagVisibility"), litPart("always"));
    return this;
  }

  modifyNametagVisibilityHideForOtherTeams(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("nametagVisibility"), litPart("hideForOtherTeams"));
    return this;
  }

  modifyNametagVisibilityHideForOwnTeam(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("nametagVisibility"), litPart("hideForOwnTeam"));
    return this;
  }

  modifyNametagVisibilityNever(team: Team): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("nametagVisibility"), litPart("never"));
    return this;
  }

  modifyPrefix(team: Team, prefix: Component): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("prefix"), argPart(prefix));
    return this;
  }

  modifySeeFriendlyInvisibles(team: Team, allowed: boolean): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("seeFriendlyInvisibles"), argPart(allowed));
    return this;
  }

  modifySuffix(team: Team, suffix: Component): this {
    this.$set(litPart("team"), litPart("modify"), argPart(team), litPart("suffix"), argPart(suffix));
    return this;
  }

  remove(team: Team): this {
    this.$set(litPart("team"), litPart("remove"), argPart(team));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `team` - `ctx.team()...` */
    team(): TeamBuilder;
  }
}

FunctionContext.prototype.team = function (this: FunctionContext) {
  const node = new TreeCommandNode("team");
  this.emit(node);
  const parts: CommandPart[] = [litPart("team")];
  node.parts = parts;
  return new TeamBuilder(node);
};
