// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Message } from "../values";

/** `teammsg` */
export class TeammsgNode extends CommandNodeBase {
  readonly type = "teammsg";
}

export class TeammsgBuilder extends CommandBuilder<TeammsgNode> {

}

export class TeammsgHandler extends TreeCommandHandler<TeammsgNode> {
  readonly type: TeammsgNode["type"] = "teammsg";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `teammsg` - `ctx.teammsg()...` */
    teammsg(message: Message): TeammsgBuilder;
  }
}

FunctionContext.prototype.teammsg = function (this: FunctionContext, message: Message) {
  const node = new TeammsgNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("teammsg"), argPart(message)];
  node.parts = parts;
  return new TeammsgBuilder(node);
};
