// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { EntityAnchor, Pos } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `teleport` */
export class TeleportNode extends CommandNodeBase {
  readonly type = "teleport";
}

export class TeleportBuilder extends CommandBuilder<TeleportNode> {
  facing(targets: Selector, location: Pos, facingLocation: Pos): this {
    this.$set(litPart("teleport"), argPart(targets), argPart(location), litPart("facing"), argPart(facingLocation));
    return this;
  }

  facingEntity(targets: Selector, location: Pos, facingEntity: Selector, facingAnchor?: EntityAnchor): this {
    this.$set(litPart("teleport"), argPart(targets), argPart(location), litPart("facing"), litPart("entity"), argPart(facingEntity));
    if (facingAnchor !== undefined) this.$append(argPart(facingAnchor));
    return this;
  }
}

export class TeleportHandler extends TreeCommandHandler<TeleportNode> {
  readonly type: TeleportNode["type"] = "teleport";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `teleport` - `ctx.teleport()...` */
    teleport(targets?: Selector, location?: Pos, rotation?: Pos): TeleportBuilder;
  }
}

FunctionContext.prototype.teleport = function (this: FunctionContext, targets?: Selector, location?: Pos, rotation?: Pos) {
  const node = new TeleportNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("teleport")];
  if (targets !== undefined) parts.push(argPart(targets));
  if (location !== undefined) parts.push(argPart(location));
  if (rotation !== undefined) parts.push(argPart(rotation));
  node.parts = parts;
  return new TeleportBuilder(node);
};
