// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Id, TestInstance } from "../values";

/** `test` */
export class TestNode extends CommandNodeBase {
  readonly type = "test";
}

export class TestBuilder extends CommandBuilder<TestNode> {
  clearall(radius?: number): this {
    this.$set(litPart("test"), litPart("clearall"));
    if (radius !== undefined) this.$append(argPart(radius));
    return this;
  }

  clearthat(): this {
    this.$set(litPart("test"), litPart("clearthat"));
    return this;
  }

  clearthese(): this {
    this.$set(litPart("test"), litPart("clearthese"));
    return this;
  }

  create(id: Id, width?: number, height?: number, depth?: number): this {
    this.$set(litPart("test"), litPart("create"), argPart(id));
    if (width !== undefined) this.$append(argPart(width));
    if (height !== undefined) this.$append(argPart(height));
    if (depth !== undefined) this.$append(argPart(depth));
    return this;
  }

  locate(tests: TestInstance): this {
    this.$set(litPart("test"), litPart("locate"), argPart(tests));
    return this;
  }

  pos(var_?: string): this {
    this.$set(litPart("test"), litPart("pos"));
    if (var_ !== undefined) this.$append(argPart(var_));
    return this;
  }

  resetclosest(): this {
    this.$set(litPart("test"), litPart("resetclosest"));
    return this;
  }

  resetthat(): this {
    this.$set(litPart("test"), litPart("resetthat"));
    return this;
  }

  resetthese(): this {
    this.$set(litPart("test"), litPart("resetthese"));
    return this;
  }

  run(tests: TestInstance, numberOfTimes?: number, untilFailed?: boolean, rotationSteps?: number, testsPerRow?: number): this {
    this.$set(litPart("test"), litPart("run"), argPart(tests));
    if (numberOfTimes !== undefined) this.$append(argPart(numberOfTimes));
    if (untilFailed !== undefined) this.$append(argPart(untilFailed));
    if (rotationSteps !== undefined) this.$append(argPart(rotationSteps));
    if (testsPerRow !== undefined) this.$append(argPart(testsPerRow));
    return this;
  }

  runclosest(numberOfTimes?: number, untilFailed?: boolean): this {
    this.$set(litPart("test"), litPart("runclosest"));
    if (numberOfTimes !== undefined) this.$append(argPart(numberOfTimes));
    if (untilFailed !== undefined) this.$append(argPart(untilFailed));
    return this;
  }

  runfailed(onlyRequiredTests?: boolean, numberOfTimes?: number, untilFailed?: boolean, rotationSteps?: number, testsPerRow?: number): this {
    this.$set(litPart("test"), litPart("runfailed"));
    if (onlyRequiredTests !== undefined) this.$append(argPart(onlyRequiredTests));
    if (numberOfTimes !== undefined) this.$append(argPart(numberOfTimes));
    if (untilFailed !== undefined) this.$append(argPart(untilFailed));
    if (rotationSteps !== undefined) this.$append(argPart(rotationSteps));
    if (testsPerRow !== undefined) this.$append(argPart(testsPerRow));
    return this;
  }

  runmultiple(tests: TestInstance, amount?: number): this {
    this.$set(litPart("test"), litPart("runmultiple"), argPart(tests));
    if (amount !== undefined) this.$append(argPart(amount));
    return this;
  }

  runthat(numberOfTimes?: number, untilFailed?: boolean): this {
    this.$set(litPart("test"), litPart("runthat"));
    if (numberOfTimes !== undefined) this.$append(argPart(numberOfTimes));
    if (untilFailed !== undefined) this.$append(argPart(untilFailed));
    return this;
  }

  runthese(numberOfTimes?: number, untilFailed?: boolean): this {
    this.$set(litPart("test"), litPart("runthese"));
    if (numberOfTimes !== undefined) this.$append(argPart(numberOfTimes));
    if (untilFailed !== undefined) this.$append(argPart(untilFailed));
    return this;
  }

  stop(): this {
    this.$set(litPart("test"), litPart("stop"));
    return this;
  }

  verify(tests: TestInstance): this {
    this.$set(litPart("test"), litPart("verify"), argPart(tests));
    return this;
  }
}

export class TestHandler extends TreeCommandHandler<TestNode> {
  readonly type: TestNode["type"] = "test";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `test` - `ctx.test()...` */
    test(): TestBuilder;
  }
}

FunctionContext.prototype.test = function (this: FunctionContext) {
  const node = new TestNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("test")];
  node.parts = parts;
  return new TestBuilder(node);
};
