// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Time } from "../values";

/** `tick` */
export class TickBuilder extends CommandBuilder<TreeCommandNode> {
  freeze(): this {
    this.$set(litPart("tick"), litPart("freeze"));
    return this;
  }

  query(): this {
    this.$set(litPart("tick"), litPart("query"));
    return this;
  }

  rate(rate: number): this {
    this.$set(litPart("tick"), litPart("rate"), argPart(rate));
    return this;
  }

  sprint(time: Time): this {
    this.$set(litPart("tick"), litPart("sprint"), argPart(time));
    return this;
  }

  sprintStop(): this {
    this.$set(litPart("tick"), litPart("sprint"), litPart("stop"));
    return this;
  }

  step(time?: Time): this {
    this.$set(litPart("tick"), litPart("step"));
    if (time !== undefined) this.$append(argPart(time));
    return this;
  }

  stepStop(): this {
    this.$set(litPart("tick"), litPart("step"), litPart("stop"));
    return this;
  }

  unfreeze(): this {
    this.$set(litPart("tick"), litPart("unfreeze"));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `tick` - `ctx.tick()...` */
    tick(): TickBuilder;
  }
}

FunctionContext.prototype.tick = function (this: FunctionContext) {
  const node = new TreeCommandNode("tick");
  this.emit(node);
  const parts: CommandPart[] = [litPart("tick")];
  node.parts = parts;
  return new TickBuilder(node);
};
