// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Time, Timeline, WorldClock } from "../values";

/** `time` */
export class TimeBuilder extends CommandBuilder<TreeCommandNode> {
  add(time: Time): this {
    this.$set(litPart("time"), litPart("add"), argPart(time));
    return this;
  }

  ofAdd(clock: WorldClock, time: Time): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("add"), argPart(time));
    return this;
  }

  ofPause(clock: WorldClock): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("pause"));
    return this;
  }

  ofQuery(clock: WorldClock, timeline: Timeline): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("query"), argPart(timeline));
    return this;
  }

  ofQueryRepetition(clock: WorldClock, timeline: Timeline): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("query"), argPart(timeline), litPart("repetition"));
    return this;
  }

  ofQueryTime(clock: WorldClock): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("query"), litPart("time"));
    return this;
  }

  ofRate(clock: WorldClock, rate: number): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("rate"), argPart(rate));
    return this;
  }

  ofResume(clock: WorldClock): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("resume"));
    return this;
  }

  ofSet(clock: WorldClock, time: Time): this {
    this.$set(litPart("time"), litPart("of"), argPart(clock), litPart("set"), argPart(time));
    return this;
  }

  pause(): this {
    this.$set(litPart("time"), litPart("pause"));
    return this;
  }

  query(timeline: Timeline): this {
    this.$set(litPart("time"), litPart("query"), argPart(timeline));
    return this;
  }

  queryGametime(): this {
    this.$set(litPart("time"), litPart("query"), litPart("gametime"));
    return this;
  }

  queryRepetition(timeline: Timeline): this {
    this.$set(litPart("time"), litPart("query"), argPart(timeline), litPart("repetition"));
    return this;
  }

  queryTime(): this {
    this.$set(litPart("time"), litPart("query"), litPart("time"));
    return this;
  }

  rate(rate: number): this {
    this.$set(litPart("time"), litPart("rate"), argPart(rate));
    return this;
  }

  resume(): this {
    this.$set(litPart("time"), litPart("resume"));
    return this;
  }

  set(time: Time): this {
    this.$set(litPart("time"), litPart("set"), argPart(time));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `time` - `ctx.time()...` */
    time(): TimeBuilder;
  }
}

FunctionContext.prototype.time = function (this: FunctionContext) {
  const node = new TreeCommandNode("time");
  this.emit(node);
  const parts: CommandPart[] = [litPart("time")];
  node.parts = parts;
  return new TimeBuilder(node);
};
