// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Component, Time } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `title` */
export class TitleNode extends CommandNodeBase {
  readonly type = "title";
}

export class TitleBuilder extends CommandBuilder<TitleNode> {
  actionbar(targets: Selector, title: Component): this {
    this.$set(litPart("title"), argPart(targets), litPart("actionbar"), argPart(title));
    return this;
  }

  clear(targets: Selector): this {
    this.$set(litPart("title"), argPart(targets), litPart("clear"));
    return this;
  }

  reset(targets: Selector): this {
    this.$set(litPart("title"), argPart(targets), litPart("reset"));
    return this;
  }

  subtitle(targets: Selector, title: Component): this {
    this.$set(litPart("title"), argPart(targets), litPart("subtitle"), argPart(title));
    return this;
  }

  times(targets: Selector, fadeIn: Time, stay: Time, fadeOut: Time): this {
    this.$set(litPart("title"), argPart(targets), litPart("times"), argPart(fadeIn), argPart(stay), argPart(fadeOut));
    return this;
  }

  title(targets: Selector, title: Component): this {
    this.$set(litPart("title"), argPart(targets), litPart("title"), argPart(title));
    return this;
  }
}

export class TitleHandler extends TreeCommandHandler<TitleNode> {
  readonly type: TitleNode["type"] = "title";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `title` - `ctx.title()...` */
    title(): TitleBuilder;
  }
}

FunctionContext.prototype.title = function (this: FunctionContext) {
  const node = new TitleNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("title")];
  node.parts = parts;
  return new TitleBuilder(node);
};
