// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `transfer` */
export class TransferNode extends CommandNodeBase {
  readonly type = "transfer";
}

export class TransferBuilder extends CommandBuilder<TransferNode> {

}

export class TransferHandler extends TreeCommandHandler<TransferNode> {
  readonly type: TransferNode["type"] = "transfer";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `transfer` - `ctx.transfer()...` */
    transfer(hostname: string, port?: number, players?: Selector): TransferBuilder;
  }
}

FunctionContext.prototype.transfer = function (this: FunctionContext, hostname: string, port?: number, players?: Selector) {
  const node = new TransferNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("transfer"), argPart(hostname)];
  if (port !== undefined) parts.push(argPart(port));
  if (players !== undefined) parts.push(argPart(players));
  node.parts = parts;
  return new TransferBuilder(node);
};
