// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart } from "./base";

/** `unpublish` */
export class UnpublishNode extends CommandNodeBase {
  readonly type = "unpublish";
}

export class UnpublishBuilder extends CommandBuilder<UnpublishNode> {

}

export class UnpublishHandler extends TreeCommandHandler<UnpublishNode> {
  readonly type: UnpublishNode["type"] = "unpublish";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `unpublish` - `ctx.unpublish()...` */
    unpublish(): UnpublishBuilder;
  }
}

FunctionContext.prototype.unpublish = function (this: FunctionContext) {
  const node = new UnpublishNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("unpublish")];
  node.parts = parts;
  return new UnpublishBuilder(node);
};
