// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { HexColor, Id, TeamColor } from "../values";
import { Selector } from "../frontend/nodes/selector";

/** `waypoint` */
export class WaypointNode extends CommandNodeBase {
  readonly type = "waypoint";
}

export class WaypointBuilder extends CommandBuilder<WaypointNode> {
  list(): this {
    this.$set(litPart("waypoint"), litPart("list"));
    return this;
  }

  modifyColor(waypoint: Selector, color: TeamColor): this {
    this.$set(litPart("waypoint"), litPart("modify"), argPart(waypoint), litPart("color"), argPart(color));
    return this;
  }

  modifyColorHex(waypoint: Selector, color: HexColor): this {
    this.$set(litPart("waypoint"), litPart("modify"), argPart(waypoint), litPart("color"), litPart("hex"), argPart(color));
    return this;
  }

  modifyColorReset(waypoint: Selector): this {
    this.$set(litPart("waypoint"), litPart("modify"), argPart(waypoint), litPart("color"), litPart("reset"));
    return this;
  }

  modifyStyleReset(waypoint: Selector): this {
    this.$set(litPart("waypoint"), litPart("modify"), argPart(waypoint), litPart("style"), litPart("reset"));
    return this;
  }

  modifyStyleSet(waypoint: Selector, style: Id): this {
    this.$set(litPart("waypoint"), litPart("modify"), argPart(waypoint), litPart("style"), litPart("set"), argPart(style));
    return this;
  }
}

export class WaypointHandler extends TreeCommandHandler<WaypointNode> {
  readonly type: WaypointNode["type"] = "waypoint";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `waypoint` - `ctx.waypoint()...` */
    waypoint(): WaypointBuilder;
  }
}

FunctionContext.prototype.waypoint = function (this: FunctionContext) {
  const node = new WaypointNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("waypoint")];
  node.parts = parts;
  return new WaypointBuilder(node);
};
