// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Time } from "../values";

/** `weather` */
export class WeatherBuilder extends CommandBuilder<TreeCommandNode> {
  clear(duration?: Time): this {
    this.$set(litPart("weather"), litPart("clear"));
    if (duration !== undefined) this.$append(argPart(duration));
    return this;
  }

  rain(duration?: Time): this {
    this.$set(litPart("weather"), litPart("rain"));
    if (duration !== undefined) this.$append(argPart(duration));
    return this;
  }

  thunder(duration?: Time): this {
    this.$set(litPart("weather"), litPart("thunder"));
    if (duration !== undefined) this.$append(argPart(duration));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `weather` - `ctx.weather()...` */
    weather(): WeatherBuilder;
  }
}

FunctionContext.prototype.weather = function (this: FunctionContext) {
  const node = new TreeCommandNode("weather");
  this.emit(node);
  const parts: CommandPart[] = [litPart("weather")];
  node.parts = parts;
  return new WeatherBuilder(node);
};
