// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandNodeBase, CommandPart } from "../ir/node";
import { TreeCommandHandler } from "../ir/tree-command";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Selector } from "../frontend/nodes/selector";

/** `whitelist` */
export class WhitelistNode extends CommandNodeBase {
  readonly type = "whitelist";
}

export class WhitelistBuilder extends CommandBuilder<WhitelistNode> {
  add(targets: Selector): this {
    this.$set(litPart("whitelist"), litPart("add"), argPart(targets));
    return this;
  }

  list(): this {
    this.$set(litPart("whitelist"), litPart("list"));
    return this;
  }

  off(): this {
    this.$set(litPart("whitelist"), litPart("off"));
    return this;
  }

  on(): this {
    this.$set(litPart("whitelist"), litPart("on"));
    return this;
  }

  reload(): this {
    this.$set(litPart("whitelist"), litPart("reload"));
    return this;
  }

  remove(targets: Selector): this {
    this.$set(litPart("whitelist"), litPart("remove"), argPart(targets));
    return this;
  }
}

export class WhitelistHandler extends TreeCommandHandler<WhitelistNode> {
  readonly type: WhitelistNode["type"] = "whitelist";
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `whitelist` - `ctx.whitelist()...` */
    whitelist(): WhitelistBuilder;
  }
}

FunctionContext.prototype.whitelist = function (this: FunctionContext) {
  const node = new WhitelistNode();
  this.emit(node);
  const parts: CommandPart[] = [litPart("whitelist")];
  node.parts = parts;
  return new WhitelistBuilder(node);
};
