// GENERATED by scripts/gen-commands.mjs -- do not edit by hand.
import { CommandPart, TreeCommandNode } from "../ir/node";
import { FunctionContext } from "../frontend/context";
import { CommandBuilder, litPart, argPart } from "./base";
import { Pos, Time } from "../values";

/** `worldborder` */
export class WorldborderBuilder extends CommandBuilder<TreeCommandNode> {
  add(distance: number, time?: Time): this {
    this.$set(litPart("worldborder"), litPart("add"), argPart(distance));
    if (time !== undefined) this.$append(argPart(time));
    return this;
  }

  center(pos: Pos): this {
    this.$set(litPart("worldborder"), litPart("center"), argPart(pos));
    return this;
  }

  damageAmount(damagePerBlock: number): this {
    this.$set(litPart("worldborder"), litPart("damage"), litPart("amount"), argPart(damagePerBlock));
    return this;
  }

  damageBuffer(distance: number): this {
    this.$set(litPart("worldborder"), litPart("damage"), litPart("buffer"), argPart(distance));
    return this;
  }

  get(): this {
    this.$set(litPart("worldborder"), litPart("get"));
    return this;
  }

  set(distance: number, time?: Time): this {
    this.$set(litPart("worldborder"), litPart("set"), argPart(distance));
    if (time !== undefined) this.$append(argPart(time));
    return this;
  }

  warningDistance(distance: number): this {
    this.$set(litPart("worldborder"), litPart("warning"), litPart("distance"), argPart(distance));
    return this;
  }

  warningTime(time: Time): this {
    this.$set(litPart("worldborder"), litPart("warning"), litPart("time"), argPart(time));
    return this;
  }
}

declare module "../frontend/context" {
  interface FunctionContext {
    /** `worldborder` - `ctx.worldborder()...` */
    worldborder(): WorldborderBuilder;
  }
}

FunctionContext.prototype.worldborder = function (this: FunctionContext) {
  const node = new TreeCommandNode("worldborder");
  this.emit(node);
  const parts: CommandPart[] = [litPart("worldborder")];
  node.parts = parts;
  return new WorldborderBuilder(node);
};
